/*! Generated by build.mjs from packs/accounting/manifest.json — do not edit. */
(function (registry) {
  registry.register("accounting", {
  "packId": "accounting",
  "version": 1,
  "hash": "",
  "languages": [
    "*"
  ],
  "accessibility": {
    "contrast": "AA",
    "reducedMotion": true,
    "notes": "Migrated from the legacy accounting.html page; parity verified by build.mjs --verify-pack."
  },
  "conformanceChecked": "2026-09-05",
  "assets": [
    "theme.css",
    "flavour.json",
    "note.json"
  ],
  "name": {
    "en": "Accounting"
  },
  "maintainer": "JAPER Technology",
  "license": "Project contribution terms (docs/development/0007-licensing-and-mark-policy)",
  "tokens": {
    "accent": "#3E7C5F",
    "font": "Tinos",
    "fontStack": "Tinos, ui-serif, Georgia, \"Times New Roman\", Times, -apple-system, BlinkMacSystemFont, \"Segoe UI\", Helvetica, Arial, \"Noto Sans\", \"Noto Sans Arabic\", \"Noto Sans Hebrew\", \"Noto Sans Bengali\", \"Noto Sans Gujarati\", \"Noto Sans Gurmukhi\", \"Noto Sans Tamil\", \"Noto Sans Telugu\", \"Noto Sans Kannada\", \"Noto Sans Malayalam\", \"Noto Sans Thai\", \"Noto Sans Ethiopic\", \"Noto Sans SC\", \"Noto Sans JP\", \"Noto Sans KR\", serif",
    "fontOptions": [],
    "defaultMode": "light",
    "onAccentDark": "#111013",
    "onAccentLight": "#FFFFFF",
    "onAccentThreshold": 0.179,
    "themeColor": "#3E7C5F"
  },
  "decorations": [
    {
      "op": "wrap",
      "anchor": ".wordmark",
      "before": "<div class=\"letterhead\">",
      "after": "</div>"
    },
    {
      "op": "insertAfter",
      "anchor": ".wordmark",
      "html": "<span class=\"workpaper-ref\"><span aria-hidden=\"true\">Workpaper ref +AI-0.1 · </span><span data-text=\"statusValue\">Draft</span></span>"
    },
    {
      "op": "prependTo",
      "anchor": ".meaning-card",
      "html": "<p class=\"card-kicker\" aria-hidden=\"true\">Summary of findings</p>"
    },
    {
      "op": "prependTo",
      "anchor": ".toc",
      "html": "<p class=\"toc-kicker\" aria-hidden=\"true\">Chart of accounts</p>"
    }
  ],
  "flavour": {
    "flavourStrings": [
      {
        "id": "draft",
        "neutral": "Draft",
        "localised": []
      },
      {
        "id": "summary-of-findings",
        "neutral": "Summary of findings",
        "localised": []
      },
      {
        "id": "chart-of-accounts",
        "neutral": "Chart of accounts",
        "localised": []
      }
    ],
    "packVersion": 1
  },
  "note": {
    "themeId": "accounting",
    "noteVersion": 1,
    "supportedFeatures": [
      {
        "feature": "hooks-contract",
        "basis": "measured",
        "by": "build.mjs --verify-pack",
        "at": "2026-09-05"
      }
    ],
    "accessibility": {
      "contrast": "AA",
      "motion": "reduced-motion-aware",
      "keyboard": "reviewed",
      "screenReader": "reviewed",
      "basis": "reviewed"
    },
    "limitations": [
      {
        "limitation": "Flavour copy is English-only at migration; other languages fall back to English via the flavour mechanism.",
        "fallback": "neutral pack",
        "blocker": false
      }
    ],
    "languageCoverage": [
      "en"
    ],
    "contentVersion": "v0.1",
    "lastCheck": {
      "at": "2026-09-05",
      "linter": "build.mjs",
      "result": "pending",
      "failedRules": []
    }
  }
});
})(window.PlusAISpecThemes);
