/*! Generated by build.mjs from packs/dec-manual/manifest.json — do not edit. */
(function (registry) {
  registry.register("dec-manual", {
  "packId": "dec-manual",
  "version": 1,
  "hash": "",
  "languages": [
    "*"
  ],
  "accessibility": {
    "contrast": "AA",
    "reducedMotion": true,
    "notes": "Migrated from the legacy dec-manual.html page; parity verified by build.mjs --verify-pack."
  },
  "conformanceChecked": "2026-09-05",
  "assets": [
    "theme.css",
    "flavour.json",
    "note.json"
  ],
  "name": {
    "en": "Dec Manual"
  },
  "maintainer": "JAPER Technology",
  "license": "Project contribution terms (docs/development/0007-licensing-and-mark-policy)",
  "tokens": {
    "accent": "#CE4A1E",
    "font": "Arimo",
    "fontStack": "Arimo, ui-sans-serif, -apple-system, BlinkMacSystemFont, \"Segoe UI\", Helvetica, Arial, \"Noto Sans\", \"Noto Sans Arabic\", \"Noto Sans Hebrew\", \"Noto Sans Bengali\", \"Noto Sans Gujarati\", \"Noto Sans Gurmukhi\", \"Noto Sans Tamil\", \"Noto Sans Telugu\", \"Noto Sans Kannada\", \"Noto Sans Malayalam\", \"Noto Sans Thai\", \"Noto Sans Ethiopic\", \"Noto Sans SC\", \"Noto Sans JP\", \"Noto Sans KR\", sans-serif",
    "fontOptions": [],
    "defaultMode": "light",
    "onAccentDark": "#111013",
    "onAccentLight": "#FFFFFF",
    "onAccentThreshold": 0.179,
    "themeColor": "#CE4A1E"
  },
  "decorations": [
    {
      "op": "setAttribute",
      "anchor": "#fontSelect",
      "name": "aria-label",
      "value": "Choose a font"
    },
    {
      "op": "wrap",
      "anchor": ".wordmark",
      "before": "<div class=\"cover-band\"><div class=\"cover-inner\">",
      "after": "</div></div>"
    },
    {
      "op": "insertAfter",
      "anchor": ".wordmark",
      "html": "<div class=\"cover-meta\"><span class=\"cover-subtitle\" data-text=\"specification\">{{flavour:specification}}</span><span class=\"cover-docno\" aria-hidden=\"true\">{{flavour:em-20260818-pn}}</span></div><div class=\"cover-edition\"><span class=\"cover-edition-label\" data-text=\"statusLabel\">{{flavour:status}}</span><span class=\"cover-edition-value\" data-text=\"statusValue\">{{flavour:draft}}</span><span class=\"cover-edition-dot\" aria-hidden=\"true\">·</span><span class=\"cover-edition-version\">0.1</span></div>"
    },
    {
      "op": "wrap",
      "anchor": ".header-controls",
      "before": "<div class=\"controls-row\">",
      "after": "</div>"
    }
  ],
  "numbering": {
    "section": "${number}.0",
    "toc": "${number}-1"
  },
  "flavour": {
    "flavourStrings": [
      {
        "id": "specification",
        "neutral": "Specification",
        "localised": []
      },
      {
        "id": "em-20260818-pn",
        "neutral": "EM-20260818-PN",
        "localised": []
      },
      {
        "id": "status",
        "neutral": "Status",
        "localised": []
      },
      {
        "id": "draft",
        "neutral": "Draft",
        "localised": []
      }
    ],
    "packVersion": 1
  },
  "note": {
    "themeId": "dec-manual",
    "noteVersion": 1,
    "supportedFeatures": [
      {
        "feature": "hooks-contract",
        "basis": "measured",
        "by": "build.mjs --verify-pack",
        "at": "2026-09-05"
      }
    ],
    "accessibility": {
      "contrast": "AA",
      "motion": "reduced-motion-aware",
      "keyboard": "reviewed",
      "screenReader": "reviewed",
      "basis": "reviewed"
    },
    "limitations": [],
    "languageCoverage": [
      "en"
    ],
    "contentVersion": "v0.1",
    "lastCheck": {
      "at": "2025-09-05",
      "linter": "build.mjs",
      "result": "passed",
      "failedRules": []
    }
  }
});
})(window.PlusAISpecThemes);
