/*! Generated by build.mjs from packs/finance/manifest.json — do not edit. */
(function (registry) {
  registry.register("finance", {
  "packId": "finance",
  "version": 1,
  "hash": "",
  "languages": [
    "*"
  ],
  "accessibility": {
    "contrast": "AA",
    "reducedMotion": true,
    "notes": "Migrated from the legacy finance.html page; parity verified by build.mjs --verify-pack."
  },
  "conformanceChecked": "2026-09-05",
  "assets": [
    "theme.css",
    "flavour.json",
    "note.json"
  ],
  "name": {
    "en": "Finance"
  },
  "maintainer": "JAPER Technology",
  "license": "Project contribution terms (docs/development/0007-licensing-and-mark-policy)",
  "tokens": {
    "accent": "#1F5C45",
    "font": "Libre Baskerville",
    "fontStack": "Libre Baskerville, ui-sans-serif, -apple-system, BlinkMacSystemFont, \"Segoe UI\", Helvetica, Arial, \"Noto Sans\", \"Noto Sans Arabic\", \"Noto Sans Hebrew\", \"Noto Sans Bengali\", \"Noto Sans Gujarati\", \"Noto Sans Gurmukhi\", \"Noto Sans Tamil\", \"Noto Sans Telugu\", \"Noto Sans Kannada\", \"Noto Sans Malayalam\", \"Noto Sans Thai\", \"Noto Sans Ethiopic\", \"Noto Sans SC\", \"Noto Sans JP\", \"Noto Sans KR\", sans-serif",
    "fontOptions": [],
    "defaultMode": "light",
    "onAccentDark": "#111013",
    "onAccentLight": "#FFFFFF",
    "onAccentThreshold": 0.179,
    "themeColor": "#1F5C45"
  },
  "decorations": [
    {
      "op": "wrap",
      "anchor": ".wordmark",
      "before": "<div class=\"header-inner\"><div class=\"letterhead\">",
      "after": "</div></div>"
    },
    {
      "op": "insertAfter",
      "anchor": ".wordmark",
      "html": "<span class=\"wordmark-tag\" aria-hidden=\"true\">{{flavour:accountability-mark}}</span>"
    },
    {
      "op": "move",
      "anchor": ".header-inner",
      "target": ".header-controls"
    },
    {
      "op": "insertAfter",
      "anchor": ".header-inner",
      "html": "<div class=\"wordmark-rule\" aria-hidden=\"true\"></div>"
    },
    {
      "op": "insertAfter",
      "anchor": ".site-header",
      "html": "<div class=\"ticker\" aria-hidden=\"true\"><div class=\"ticker-track\"><div class=\"ticker-run\"><span class=\"tk-accent\">+AI 0.1</span><span class=\"tk-sep\">▲</span><span class=\"tk\">{{flavour:responsibility-100}}</span><span class=\"tk-sep\">·</span><span class=\"tk\">{{flavour:mark}}+AI</span><span class=\"tk-sep\">·</span><span class=\"tk\"><span data-text=\"statusLabel\">{{flavour:status}}</span><span data-text=\"statusValue\">{{flavour:draft}}</span></span><span class=\"tk-sep\">·</span><span class=\"tk\">{{flavour:human-accountability}}</span><span class=\"tk-sep\">·</span><span class=\"tk\">{{flavour:canonical}}+AI</span><span class=\"tk-sep\">▲</span></div><div class=\"ticker-run\"><span class=\"tk-accent\">+AI 0.1</span><span class=\"tk-sep\">▲</span><span class=\"tk\">{{flavour:flavour-1}}</span><span class=\"tk-sep\">·</span><span class=\"tk\">{{flavour:flavour-2}}+AI</span><span class=\"tk-sep\">·</span><span class=\"tk\"><span data-text=\"statusLabel\">{{flavour:flavour-3}}</span><span data-text=\"statusValue\">{{flavour:flavour-4}}</span></span><span class=\"tk-sep\">·</span><span class=\"tk\">{{flavour:flavour-5}}</span><span class=\"tk-sep\">·</span><span class=\"tk\">{{flavour:flavour-6}}+AI</span><span class=\"tk-sep\">▲</span></div></div></div>"
    }
  ],
  "flavour": {
    "flavourStrings": [
      {
        "id": "accountability-mark",
        "neutral": "Accountability Mark",
        "localised": []
      },
      {
        "id": "responsibility-100",
        "neutral": "RESPONSIBILITY 100%",
        "localised": []
      },
      {
        "id": "mark",
        "neutral": "MARK ",
        "localised": []
      },
      {
        "id": "status",
        "neutral": "Status",
        "localised": []
      },
      {
        "id": "draft",
        "neutral": "Draft",
        "localised": []
      },
      {
        "id": "human-accountability",
        "neutral": "HUMAN ACCOUNTABILITY",
        "localised": []
      },
      {
        "id": "canonical",
        "neutral": "CANONICAL ",
        "localised": []
      },
      {
        "id": "flavour-1",
        "neutral": "RESPONSIBILITY 100%",
        "localised": []
      },
      {
        "id": "flavour-2",
        "neutral": "MARK ",
        "localised": []
      },
      {
        "id": "flavour-3",
        "neutral": "Status",
        "localised": []
      },
      {
        "id": "flavour-4",
        "neutral": "Draft",
        "localised": []
      },
      {
        "id": "flavour-5",
        "neutral": "HUMAN ACCOUNTABILITY",
        "localised": []
      },
      {
        "id": "flavour-6",
        "neutral": "CANONICAL ",
        "localised": []
      }
    ],
    "packVersion": 1
  },
  "note": {
    "themeId": "finance",
    "noteVersion": 1,
    "supportedFeatures": [
      {
        "feature": "hooks-contract",
        "basis": "measured",
        "by": "build.mjs --verify-pack",
        "at": "2026-09-05"
      }
    ],
    "accessibility": {
      "contrast": "AA",
      "motion": "reduced-motion-aware",
      "keyboard": "reviewed",
      "screenReader": "reviewed",
      "basis": "reviewed"
    },
    "limitations": [],
    "languageCoverage": [
      "en"
    ],
    "contentVersion": "v0.1",
    "lastCheck": {
      "at": "2025-09-05",
      "linter": "build.mjs",
      "result": "passed",
      "failedRules": []
    }
  }
});
})(window.PlusAISpecThemes);
