/*! Generated by build.mjs from packs/maritime/manifest.json — do not edit. */
(function (registry) {
  registry.register("maritime", {
  "packId": "maritime",
  "version": 1,
  "hash": "",
  "languages": [
    "*"
  ],
  "accessibility": {
    "contrast": "AA",
    "reducedMotion": true,
    "notes": "Migrated from the legacy maritime.html page; parity verified by build.mjs --verify-pack."
  },
  "conformanceChecked": "2026-09-05",
  "assets": [
    "theme.css",
    "flavour.json",
    "note.json"
  ],
  "name": {
    "en": "Maritime"
  },
  "maintainer": "JAPER Technology",
  "license": "Project contribution terms (docs/development/0007-licensing-and-mark-policy)",
  "tokens": {
    "accent": "#1B4F72",
    "font": "Source Sans 3",
    "fontStack": "\"Source Sans 3\", ui-sans-serif, -apple-system, BlinkMacSystemFont, \"Segoe UI\", Helvetica, Arial, \"Noto Sans\", \"Noto Sans Arabic\", \"Noto Sans Hebrew\", \"Noto Sans Bengali\", \"Noto Sans Gujarati\", \"Noto Sans Gurmukhi\", \"Noto Sans Tamil\", \"Noto Sans Telugu\", \"Noto Sans Kannada\", \"Noto Sans Malayalam\", \"Noto Sans Thai\", \"Noto Sans Ethiopic\", \"Noto Sans SC\", \"Noto Sans JP\", \"Noto Sans KR\", sans-serif",
    "fontOptions": [],
    "defaultMode": "light",
    "onAccentDark": "#1B2A35",
    "onAccentLight": "#FFFFFF",
    "onAccentThreshold": 0.179,
    "themeColor": "#1B4F72"
  },
  "decorations": [
    {
      "op": "insertBefore",
      "anchor": ".skip-link",
      "html": "<div class=\"graticule\" aria-hidden=\"true\"></div>"
    },
    {
      "op": "prependTo",
      "anchor": ".site-header",
      "html": "<div class=\"notice-band\"><div class=\"notice-band-inner\"><span class=\"band-title\">{{flavour:notice-to-mariners}}</span><span class=\"band-readout\"><span class=\"band-no\">{{flavour:notice-no}}+AI-0.1</span><span class=\"band-sep\" aria-hidden=\"true\">·</span><span class=\"band-status\"><span data-text=\"statusLabel\">{{flavour:status}}</span>:<span data-text=\"statusValue\">{{flavour:draft}}</span></span></span></div></div>"
    },
    {
      "op": "insertAfter",
      "anchor": ".notice-band",
      "html": "<div class=\"header-row\"></div>"
    },
    {
      "op": "move",
      "anchor": ".header-row",
      "target": ".wordmark"
    },
    {
      "op": "move",
      "anchor": ".header-row",
      "target": ".header-controls"
    },
    {
      "op": "prependTo",
      "anchor": "#meaning",
      "html": "<div class=\"compass\" aria-hidden=\"true\"><div class=\"rose\"><i class=\"rose-diag rose-diag-a\"></i><i class=\"rose-diag rose-diag-b\"></i><span class=\"rose-letter rose-n\">{{flavour:n}}</span><span class=\"rose-letter rose-e\">{{flavour:e}}</span><span class=\"rose-letter rose-s\">{{flavour:s}}</span><span class=\"rose-letter rose-w\">{{flavour:w}}</span></div></div>"
    },
    {
      "op": "prependTo",
      "anchor": ".plain-meaning",
      "html": "<div class=\"scale-bar\" aria-hidden=\"true\"><span class=\"scale-rule\"><i></i><i></i><i></i><i></i><i></i></span><span class=\"scale-label\">{{flavour:0-1-2-3-4-nm}}</span></div>"
    },
    {
      "op": "text",
      "anchor": "#specTitle",
      "html": "<span class=\"mark\">+AI</span><span data-text=\"specification\">{{flavour:specification}}</span>"
    },
    {
      "op": "wrap",
      "anchor": ".spec-meta",
      "before": "<div class=\"chart-data\"><span class=\"chart-data-title\" aria-hidden=\"true\">{{flavour:chart-data}}</span>",
      "after": "</div>"
    }
  ],
  "flavour": {
    "flavourStrings": [
      {
        "id": "notice-to-mariners",
        "neutral": "Notice to Mariners",
        "localised": []
      },
      {
        "id": "notice-no",
        "neutral": "Notice No. ",
        "localised": []
      },
      {
        "id": "status",
        "neutral": "Status",
        "localised": []
      },
      {
        "id": "draft",
        "neutral": "Draft",
        "localised": []
      },
      {
        "id": "n",
        "neutral": "N",
        "localised": []
      },
      {
        "id": "e",
        "neutral": "E",
        "localised": []
      },
      {
        "id": "s",
        "neutral": "S",
        "localised": []
      },
      {
        "id": "w",
        "neutral": "W",
        "localised": []
      },
      {
        "id": "0-1-2-3-4-nm",
        "neutral": "0 · 1 · 2 · 3 · 4 NM",
        "localised": []
      },
      {
        "id": "specification",
        "neutral": "Specification",
        "localised": []
      },
      {
        "id": "chart-data",
        "neutral": "Chart Data",
        "localised": []
      }
    ],
    "packVersion": 1
  },
  "note": {
    "themeId": "maritime",
    "noteVersion": 1,
    "supportedFeatures": [
      {
        "feature": "hooks-contract",
        "basis": "measured",
        "by": "build.mjs --verify-pack",
        "at": "2026-09-05"
      }
    ],
    "accessibility": {
      "contrast": "AA",
      "motion": "reduced-motion-aware",
      "keyboard": "reviewed",
      "screenReader": "reviewed",
      "basis": "reviewed"
    },
    "limitations": [],
    "languageCoverage": [
      "en"
    ],
    "contentVersion": "v0.1",
    "lastCheck": {
      "at": "2025-09-05",
      "linter": "build.mjs",
      "result": "passed",
      "failedRules": []
    }
  }
});
})(window.PlusAISpecThemes);
