/*! Generated by build.mjs from packs/fintech/manifest.json — do not edit. */
(function (registry) {
  registry.register("fintech", {
  "packId": "fintech",
  "version": 1,
  "hash": "",
  "languages": [
    "*"
  ],
  "accessibility": {
    "contrast": "AA",
    "reducedMotion": true,
    "notes": "Migrated from the legacy fintech.html page; parity verified by build.mjs --verify-pack."
  },
  "conformanceChecked": "2026-09-05",
  "assets": [
    "theme.css",
    "flavour.json",
    "note.json"
  ],
  "name": {
    "en": "Fintech"
  },
  "maintainer": "JAPER Technology",
  "license": "Project contribution terms (docs/development/0007-licensing-and-mark-policy)",
  "tokens": {
    "accent": "#2CE5A7",
    "font": "Manrope",
    "fontStack": "Manrope, ui-sans-serif, -apple-system, BlinkMacSystemFont, \"Segoe UI\", Helvetica, Arial, \"Noto Sans\", \"Noto Sans Arabic\", \"Noto Sans Hebrew\", \"Noto Sans Bengali\", \"Noto Sans Gujarati\", \"Noto Sans Gurmukhi\", \"Noto Sans Tamil\", \"Noto Sans Telugu\", \"Noto Sans Kannada\", \"Noto Sans Malayalam\", \"Noto Sans Thai\", \"Noto Sans Ethiopic\", \"Noto Sans SC\", \"Noto Sans JP\", \"Noto Sans KR\", sans-serif",
    "fontOptions": [],
    "defaultMode": "dark",
    "onAccentDark": "#111013",
    "onAccentLight": "#FFFFFF",
    "onAccentThreshold": 0.179,
    "themeColor": "#2CE5A7"
  },
  "decorations": [
    {
      "op": "appendTo",
      "anchor": ".wordmark",
      "html": "<span class=\"wordmark-dot\" aria-hidden=\"true\"></span>"
    },
    {
      "op": "insertAfter",
      "anchor": ".site-header",
      "html": "<div class=\"ticker\" aria-hidden=\"true\"><div class=\"ticker-track\"><div class=\"ticker-group\"><span class=\"ticker-item\">+AI 0.1</span><span class=\"ticker-arrow\">▲</span><span class=\"ticker-dot\">·</span><span class=\"ticker-item\">{{flavour:responsibility-100}}</span><span class=\"ticker-dot\">·</span><span class=\"ticker-item\">{{flavour:mark}}+AI</span><span class=\"ticker-dot\">·</span><span class=\"ticker-item ticker-status\" data-text=\"statusValue\">{{flavour:draft}}</span></div><div class=\"ticker-group\"><span class=\"ticker-item\">+AI 0.1</span><span class=\"ticker-arrow\">▲</span><span class=\"ticker-dot\">·</span><span class=\"ticker-item\">{{flavour:flavour-1}}</span><span class=\"ticker-dot\">·</span><span class=\"ticker-item\">{{flavour:flavour-2}}+AI</span><span class=\"ticker-dot\">·</span><span class=\"ticker-item ticker-status\" data-text=\"statusValue\">{{flavour:flavour-3}}</span></div></div></div>"
    },
    {
      "op": "insertAfter",
      "anchor": ".primary-link",
      "html": "<span class=\"status-chip\" aria-hidden=\"true\">{{flavour:settled}}</span>"
    },
    {
      "op": "prependTo",
      "anchor": ".meaning-card",
      "html": "<span class=\"panel-label\" aria-hidden=\"true\">{{flavour:the-stack}}</span>"
    },
    {
      "op": "wrap",
      "anchor": ".spec-meta",
      "before": "<div class=\"spec-header-meta\"><span class=\"status-chip\" aria-hidden=\"true\">{{flavour:confirmed}}</span>",
      "after": "</div>"
    },
    {
      "op": "prependTo",
      "anchor": ".toc",
      "html": "<span class=\"panel-label\" aria-hidden=\"true\">{{flavour:products}}</span>"
    }
  ],
  "flavour": {
    "flavourStrings": [
      {
        "id": "responsibility-100",
        "neutral": "Responsibility 100%",
        "localised": []
      },
      {
        "id": "mark",
        "neutral": "Mark ",
        "localised": []
      },
      {
        "id": "draft",
        "neutral": "Draft",
        "localised": []
      },
      {
        "id": "flavour-1",
        "neutral": "Responsibility 100%",
        "localised": []
      },
      {
        "id": "flavour-2",
        "neutral": "Mark ",
        "localised": []
      },
      {
        "id": "flavour-3",
        "neutral": "Draft",
        "localised": []
      },
      {
        "id": "settled",
        "neutral": "Settled",
        "localised": []
      },
      {
        "id": "the-stack",
        "neutral": "The Stack",
        "localised": []
      },
      {
        "id": "confirmed",
        "neutral": "Confirmed",
        "localised": []
      },
      {
        "id": "products",
        "neutral": "Products",
        "localised": []
      }
    ],
    "packVersion": 1
  },
  "note": {
    "themeId": "fintech",
    "noteVersion": 1,
    "supportedFeatures": [
      {
        "feature": "hooks-contract",
        "basis": "measured",
        "by": "build.mjs --verify-pack",
        "at": "2026-09-05"
      }
    ],
    "accessibility": {
      "contrast": "AA",
      "motion": "reduced-motion-aware",
      "keyboard": "reviewed",
      "screenReader": "reviewed",
      "basis": "reviewed"
    },
    "limitations": [],
    "languageCoverage": [
      "en"
    ],
    "contentVersion": "v0.1",
    "lastCheck": {
      "at": "2025-09-05",
      "linter": "build.mjs",
      "result": "passed",
      "failedRules": []
    }
  }
});
})(window.PlusAISpecThemes);
