/*! Generated by build.mjs from packs/legal/manifest.json — do not edit. */
(function (registry) {
  registry.register("legal", {
  "packId": "legal",
  "version": 1,
  "hash": "",
  "languages": [
    "*"
  ],
  "accessibility": {
    "contrast": "AA",
    "reducedMotion": true,
    "notes": "Migrated from the legacy legal.html page; parity verified by build.mjs --verify-pack."
  },
  "conformanceChecked": "2026-09-05",
  "assets": [
    "theme.css",
    "flavour.json",
    "note.json"
  ],
  "name": {
    "en": "Legal"
  },
  "maintainer": "JAPER Technology",
  "license": "Project contribution terms (docs/development/0007-licensing-and-mark-policy)",
  "tokens": {
    "accent": "#B08D3E",
    "font": "Lora",
    "fontStack": "Lora, ui-sans-serif, -apple-system, BlinkMacSystemFont, \"Segoe UI\", Helvetica, Arial, \"Noto Sans\", \"Noto Sans Arabic\", \"Noto Sans Hebrew\", \"Noto Sans Bengali\", \"Noto Sans Gujarati\", \"Noto Sans Gurmukhi\", \"Noto Sans Tamil\", \"Noto Sans Telugu\", \"Noto Sans Kannada\", \"Noto Sans Malayalam\", \"Noto Sans Thai\", \"Noto Sans Ethiopic\", \"Noto Sans SC\", \"Noto Sans JP\", \"Noto Sans KR\", sans-serif",
    "fontOptions": [],
    "defaultMode": "dark",
    "onAccentDark": "#111013",
    "onAccentLight": "#FFFFFF",
    "onAccentThreshold": 0.179,
    "themeColor": "#B08D3E"
  },
  "decorations": [
    {
      "op": "wrapInner",
      "anchor": ".site-header",
      "before": "<div class=\"header-row\">",
      "after": "</div>"
    },
    {
      "op": "insertAfter",
      "anchor": ".wordmark",
      "html": "<p class=\"case-file\" dir=\"ltr\" aria-hidden=\"true\"><span class=\"file-no\">{{flavour:file-no}}+AI-0.1</span><span class=\"file-sep\">·</span><span class=\"file-status\" data-text=\"statusValue\">{{flavour:draft}}</span></p>"
    },
    {
      "op": "insertAfter",
      "anchor": ".eyebrow",
      "html": "<p class=\"case-caption\" dir=\"ltr\" aria-hidden=\"true\">{{flavour:in-the-matter-of-the}}+AI{{flavour:declaration}}</p>"
    },
    {
      "op": "prependTo",
      "anchor": ".meaning-card",
      "html": "<p class=\"panel-kicker\" aria-hidden=\"true\">{{flavour:particulars}}</p>"
    },
    {
      "op": "prependTo",
      "anchor": "#untranslatedNote",
      "html": "<span class=\"notice-label\" aria-hidden=\"true\">{{flavour:notice-to-reader}}</span>"
    },
    {
      "op": "prependTo",
      "anchor": ".toc",
      "html": "<p class=\"toc-kicker\" aria-hidden=\"true\">{{flavour:table-of-clauses}}</p>"
    }
  ],
  "flavour": {
    "flavourStrings": [
      {
        "id": "file-no",
        "neutral": "FILE NO. ",
        "localised": []
      },
      {
        "id": "draft",
        "neutral": "Draft",
        "localised": []
      },
      {
        "id": "in-the-matter-of-the",
        "neutral": "In the matter of the ",
        "localised": []
      },
      {
        "id": "declaration",
        "neutral": " declaration",
        "localised": []
      },
      {
        "id": "particulars",
        "neutral": "Particulars",
        "localised": []
      },
      {
        "id": "notice-to-reader",
        "neutral": "Notice to Reader",
        "localised": []
      },
      {
        "id": "table-of-clauses",
        "neutral": "Table of Clauses",
        "localised": []
      }
    ],
    "packVersion": 1
  },
  "note": {
    "themeId": "legal",
    "noteVersion": 1,
    "supportedFeatures": [
      {
        "feature": "hooks-contract",
        "basis": "measured",
        "by": "build.mjs --verify-pack",
        "at": "2026-09-05"
      }
    ],
    "accessibility": {
      "contrast": "AA",
      "motion": "reduced-motion-aware",
      "keyboard": "reviewed",
      "screenReader": "reviewed",
      "basis": "reviewed"
    },
    "limitations": [],
    "languageCoverage": [
      "en"
    ],
    "contentVersion": "v0.1",
    "lastCheck": {
      "at": "2025-09-05",
      "linter": "build.mjs",
      "result": "passed",
      "failedRules": []
    }
  }
});
})(window.PlusAISpecThemes);
