/*! Generated by build.mjs from packs/sci-fi-1/manifest.json — do not edit. */
(function (registry) {
  registry.register("sci-fi-1", {
  "packId": "sci-fi-1",
  "version": 1,
  "hash": "",
  "languages": [
    "*"
  ],
  "accessibility": {
    "contrast": "AA",
    "reducedMotion": true,
    "notes": "Migrated from the legacy sci-fi-1.html page; parity verified by build.mjs --verify-pack."
  },
  "conformanceChecked": "2026-09-05",
  "assets": [
    "theme.css",
    "flavour.json",
    "note.json"
  ],
  "name": {
    "en": "Sci Fi 1"
  },
  "maintainer": "JAPER Technology",
  "license": "Project contribution terms (docs/development/0007-licensing-and-mark-policy)",
  "tokens": {
    "accent": "#35D0FF",
    "font": "Exo 2",
    "fontStack": "\"Exo 2\", ui-sans-serif, -apple-system, BlinkMacSystemFont, \"Segoe UI\", Helvetica, Arial, \"Noto Sans\", \"Noto Sans Arabic\", \"Noto Sans Hebrew\", \"Noto Sans Bengali\", \"Noto Sans Gujarati\", \"Noto Sans Gurmukhi\", \"Noto Sans Tamil\", \"Noto Sans Telugu\", \"Noto Sans Kannada\", \"Noto Sans Malayalam\", \"Noto Sans Thai\", \"Noto Sans Ethiopic\", \"Noto Sans SC\", \"Noto Sans JP\", \"Noto Sans KR\", sans-serif",
    "fontOptions": [],
    "defaultMode": "dark",
    "onAccentDark": "#111013",
    "onAccentLight": "#FFFFFF",
    "onAccentThreshold": 0.179,
    "themeColor": "#35D0FF"
  },
  "decorations": [
    {
      "op": "insertBefore",
      "anchor": ".skip-link",
      "html": "<div class=\"space\" aria-hidden=\"true\"></div>"
    },
    {
      "op": "setAttribute",
      "anchor": "#fontSelect",
      "name": "aria-label",
      "value": "Choose a font"
    },
    {
      "op": "prependTo",
      "anchor": ".site-header",
      "html": "<div class=\"telemetry\" aria-hidden=\"true\"><span class=\"t-readout t-pulse\"></span><span class=\"t-readout\">{{flavour:sys}} <b>+AI</b></span><span class=\"t-readout\">{{flavour:spec}} <b>0.1</b></span><span class=\"t-readout t-spacer t-optional\">{{flavour:orbital-link-nominal}}</span></div>"
    },
    {
      "op": "insertAfter",
      "anchor": ".telemetry",
      "html": "<div class=\"header-row\"></div>"
    },
    {
      "op": "move",
      "anchor": ".header-row",
      "target": ".wordmark"
    },
    {
      "op": "move",
      "anchor": ".header-row",
      "target": ".header-controls"
    },
    {
      "op": "wrap",
      "anchor": "h1#heroTitle",
      "before": "<div class=\"mark-frame\">",
      "after": "</div>"
    },
    {
      "op": "insertAfter",
      "anchor": "#heroTitle",
      "html": "<span class=\"holo-scan\" aria-hidden=\"true\"></span>"
    },
    {
      "op": "text",
      "anchor": "#specTitle",
      "html": "<span class=\"mark-glyph\">+AI</span><span data-text=\"specification\">Specification</span>"
    }
  ],
  "flavour": {
    "flavourStrings": [
      {
        "id": "sys",
        "neutral": "SYS://",
        "localised": []
      },
      {
        "id": "spec",
        "neutral": "SPEC",
        "localised": []
      },
      {
        "id": "orbital-link-nominal",
        "neutral": "ORBITAL LINK · NOMINAL",
        "localised": []
      }
    ],
    "packVersion": 1
  },
  "note": {
    "themeId": "sci-fi-1",
    "noteVersion": 1,
    "supportedFeatures": [
      {
        "feature": "hooks-contract",
        "basis": "measured",
        "by": "build.mjs --verify-pack",
        "at": "2026-09-05"
      }
    ],
    "accessibility": {
      "contrast": "AA",
      "motion": "reduced-motion-aware",
      "keyboard": "reviewed",
      "screenReader": "reviewed",
      "basis": "reviewed"
    },
    "limitations": [
      {
        "limitation": "Flavour copy is English-only at migration; other languages fall back to English via the flavour mechanism.",
        "fallback": "neutral pack",
        "blocker": false
      }
    ],
    "languageCoverage": [
      "en"
    ],
    "contentVersion": "v0.1",
    "lastCheck": {
      "at": "2025-09-05",
      "linter": "build.mjs",
      "result": "passed",
      "failedRules": []
    }
  }
});
})(window.PlusAISpecThemes);
