/*! Generated by build.mjs from packs/luxury/manifest.json — do not edit. */
(function (registry) {
  registry.register("luxury", {
  "packId": "luxury",
  "version": 1,
  "hash": "",
  "languages": [
    "*"
  ],
  "accessibility": {
    "contrast": "AA",
    "reducedMotion": true,
    "notes": "Migrated from the legacy luxury.html page; parity verified by build.mjs --verify-pack."
  },
  "conformanceChecked": "2026-09-05",
  "assets": [
    "theme.css",
    "flavour.json",
    "note.json"
  ],
  "name": {
    "en": "Luxury"
  },
  "maintainer": "JAPER Technology",
  "license": "Project contribution terms (docs/development/0007-licensing-and-mark-policy)",
  "tokens": {
    "accent": "#A98B5F",
    "font": "Spectral",
    "fontStack": "Spectral, ui-sans-serif, -apple-system, BlinkMacSystemFont, \"Segoe UI\", Helvetica, Arial, \"Noto Sans\", \"Noto Sans Arabic\", \"Noto Sans Hebrew\", \"Noto Sans Bengali\", \"Noto Sans Gujarati\", \"Noto Sans Gurmukhi\", \"Noto Sans Tamil\", \"Noto Sans Telugu\", \"Noto Sans Kannada\", \"Noto Sans Malayalam\", \"Noto Sans Thai\", \"Noto Sans Ethiopic\", \"Noto Sans SC\", \"Noto Sans JP\", \"Noto Sans KR\", sans-serif",
    "fontOptions": [],
    "defaultMode": "light",
    "onAccentDark": "#111013",
    "onAccentLight": "#FFFFFF",
    "onAccentThreshold": 0.179,
    "themeColor": "#A98B5F"
  },
  "decorations": [
    {
      "op": "text",
      "anchor": ".number",
      "html": "{{flavour:i}}"
    },
    {
      "op": "setAttribute",
      "anchor": ".number",
      "name": "class",
      "value": "num-done"
    },
    {
      "op": "text",
      "anchor": ".number",
      "html": "{{flavour:ii}}"
    },
    {
      "op": "setAttribute",
      "anchor": ".number",
      "name": "class",
      "value": "num-done"
    },
    {
      "op": "text",
      "anchor": ".number",
      "html": "{{flavour:iii}}"
    },
    {
      "op": "setAttribute",
      "anchor": ".number",
      "name": "class",
      "value": "num-done"
    },
    {
      "op": "setAttribute",
      "anchor": ".num-done",
      "name": "class",
      "value": "number"
    },
    {
      "op": "setAttribute",
      "anchor": ".num-done",
      "name": "class",
      "value": "number"
    },
    {
      "op": "setAttribute",
      "anchor": ".num-done",
      "name": "class",
      "value": "number"
    }
  ],
  "flavour": {
    "flavourStrings": [
      {
        "id": "i",
        "neutral": "I",
        "localised": []
      },
      {
        "id": "ii",
        "neutral": "II",
        "localised": []
      },
      {
        "id": "iii",
        "neutral": "III",
        "localised": []
      }
    ],
    "packVersion": 1
  },
  "note": {
    "themeId": "luxury",
    "noteVersion": 1,
    "supportedFeatures": [
      {
        "feature": "hooks-contract",
        "basis": "measured",
        "by": "build.mjs --verify-pack",
        "at": "2026-09-05"
      }
    ],
    "accessibility": {
      "contrast": "AA",
      "motion": "reduced-motion-aware",
      "keyboard": "reviewed",
      "screenReader": "reviewed",
      "basis": "reviewed"
    },
    "limitations": [],
    "languageCoverage": [
      "en"
    ],
    "contentVersion": "v0.1",
    "lastCheck": {
      "at": "2025-09-05",
      "linter": "build.mjs",
      "result": "passed",
      "failedRules": []
    }
  }
});
})(window.PlusAISpecThemes);
