/*! Generated by build.mjs from packs/university/manifest.json — do not edit. */
(function (registry) {
  registry.register("university", {
  "packId": "university",
  "version": 1,
  "hash": "",
  "languages": [
    "*"
  ],
  "accessibility": {
    "contrast": "AA",
    "reducedMotion": true,
    "notes": "Migrated from the legacy university.html page; parity verified by build.mjs --verify-pack."
  },
  "conformanceChecked": "2026-09-05",
  "assets": [
    "theme.css",
    "flavour.json",
    "note.json"
  ],
  "name": {
    "en": "University"
  },
  "maintainer": "JAPER Technology",
  "license": "Project contribution terms (docs/development/0007-licensing-and-mark-policy)",
  "tokens": {
    "accent": "#8C2236",
    "font": "Playfair Display",
    "fontStack": "\"Playfair Display\", ui-sans-serif, -apple-system, BlinkMacSystemFont, \"Segoe UI\", Helvetica, Arial, \"Noto Sans\", \"Noto Sans Arabic\", \"Noto Sans Hebrew\", \"Noto Sans Bengali\", \"Noto Sans Gujarati\", \"Noto Sans Gurmukhi\", \"Noto Sans Tamil\", \"Noto Sans Telugu\", \"Noto Sans Kannada\", \"Noto Sans Malayalam\", \"Noto Sans Thai\", \"Noto Sans Ethiopic\", \"Noto Sans SC\", \"Noto Sans JP\", \"Noto Sans KR\", sans-serif",
    "fontOptions": [],
    "defaultMode": "light",
    "onAccentDark": "#111013",
    "onAccentLight": "#FFFFFF",
    "onAccentThreshold": 0.179,
    "themeColor": "#8C2236"
  },
  "decorations": [
    {
      "op": "text",
      "anchor": ".wordmark",
      "html": "<span class=\"crest\" aria-hidden=\"true\"><span class=\"crest-mark\">+AI</span></span> <span class=\"wordmark-text\">+AI</span>"
    },
    {
      "op": "text",
      "anchor": ".meaning-list",
      "html": "<div> <span class=\"number\" aria-hidden=\"true\">I</span> <dt data-text=\"meaningOneTitle\">AI participated</dt> <dd data-text=\"meaningOneBody\">AI materially helped create, analyse, transform or present the work.</dd> </div> <div> <span class=\"number\" aria-hidden=\"true\">II</span> <dt data-text=\"meaningTwoTitle\">A human chose</dt> <dd data-text=\"meaningTwoBody\">A person or organisation knowingly adopted and released the result.</dd> </div> <div> <span class=\"number\" aria-hidden=\"true\">III</span> <dt data-text=\"meaningThreeTitle\">Responsibility stays human</dt> <dd data-text=\"meaningThreeBody\">The named party does not transfer accountability to an AI system or provider.</dd> </div>"
    },
    {
      "op": "prependTo",
      "anchor": ".hero-copy",
      "html": "<span class=\"crest crest-hero\" aria-hidden=\"true\"><span class=\"crest-mark\">+AI</span></span>"
    }
  ],
  "flavour": {
    "flavourStrings": [
      {
        "id": "i",
        "neutral": "I",
        "localised": []
      },
      {
        "id": "ii",
        "neutral": "II",
        "localised": []
      },
      {
        "id": "iii",
        "neutral": "III",
        "localised": []
      }
    ],
    "packVersion": 1
  },
  "note": {
    "themeId": "university",
    "noteVersion": 1,
    "supportedFeatures": [
      {
        "feature": "hooks-contract",
        "basis": "measured",
        "by": "build.mjs --verify-pack",
        "at": "2026-09-05"
      }
    ],
    "accessibility": {
      "contrast": "AA",
      "motion": "reduced-motion-aware",
      "keyboard": "reviewed",
      "screenReader": "reviewed",
      "basis": "reviewed"
    },
    "limitations": [
      {
        "limitation": "Flavour copy is English-only at migration; other languages fall back to English via the flavour mechanism.",
        "fallback": "neutral pack",
        "blocker": false
      }
    ],
    "languageCoverage": [
      "en"
    ],
    "contentVersion": "v0.1",
    "lastCheck": {
      "at": "2026-09-05",
      "linter": "build.mjs",
      "result": "pending",
      "failedRules": []
    }
  }
});
})(window.PlusAISpecThemes);
