/*! Generated by build.mjs from packs/insurance/manifest.json — do not edit. */
(function (registry) {
  registry.register("insurance", {
  "packId": "insurance",
  "version": 1,
  "hash": "",
  "languages": [
    "*"
  ],
  "accessibility": {
    "contrast": "AA",
    "reducedMotion": true,
    "notes": "Migrated from the legacy insurance.html page; parity verified by build.mjs --verify-pack."
  },
  "conformanceChecked": "2026-09-05",
  "assets": [
    "theme.css",
    "flavour.json",
    "note.json"
  ],
  "name": {
    "en": "Insurance"
  },
  "maintainer": "JAPER Technology",
  "license": "Project contribution terms (docs/development/0007-licensing-and-mark-policy)",
  "tokens": {
    "accent": "#1F5F9E",
    "font": "Rubik",
    "fontStack": "Rubik, ui-sans-serif, -apple-system, BlinkMacSystemFont, \"Segoe UI\", Helvetica, Arial, \"Noto Sans\", \"Noto Sans Arabic\", \"Noto Sans Hebrew\", \"Noto Sans Bengali\", \"Noto Sans Gujarati\", \"Noto Sans Gurmukhi\", \"Noto Sans Tamil\", \"Noto Sans Telugu\", \"Noto Sans Kannada\", \"Noto Sans Malayalam\", \"Noto Sans Thai\", \"Noto Sans Ethiopic\", \"Noto Sans SC\", \"Noto Sans JP\", \"Noto Sans KR\", sans-serif",
    "fontOptions": [],
    "defaultMode": "light",
    "onAccentDark": "#111013",
    "onAccentLight": "#FFFFFF",
    "onAccentThreshold": 0.179,
    "themeColor": "#1F5F9E"
  },
  "decorations": [
    {
      "op": "wrapInner",
      "anchor": ".site-header",
      "before": "<div class=\"header-bar\">",
      "after": "</div>"
    },
    {
      "op": "text",
      "anchor": ".wordmark",
      "html": "<span class=\"umbrella umbrella-sm\" aria-hidden=\"true\"><span class=\"umbrella-canopy\"></span><span class=\"umbrella-shaft\"></span><span class=\"umbrella-hook\"></span></span><span class=\"wordmark-text\">+AI</span>"
    },
    {
      "op": "insertAfter",
      "anchor": ".wordmark",
      "html": "<p class=\"policy-line\" aria-hidden=\"true\"><span>{{flavour:policy}}+AI-0.1</span><span class=\"policy-sep\">·</span><span data-text=\"statusValue\">{{flavour:draft}}</span></p>"
    },
    {
      "op": "prependTo",
      "anchor": ".hero-copy",
      "html": "<span class=\"umbrella umbrella-lg\" aria-hidden=\"true\"><span class=\"umbrella-canopy\"></span><span class=\"umbrella-shaft\"></span><span class=\"umbrella-hook\"></span></span>"
    },
    {
      "op": "prependTo",
      "anchor": ".meaning-card",
      "html": "<p class=\"card-eyebrow\" aria-hidden=\"true\">{{flavour:what-this-covers}}</p>"
    },
    {
      "op": "prependTo",
      "anchor": ".spec-meta",
      "html": "<div class=\"spec-meta-title\" aria-hidden=\"true\">{{flavour:policy-details}}</div>"
    },
    {
      "op": "replaceWith",
      "anchor": "#tocTitle",
      "html": "<h3 id=\"tocTitle\"><span class=\"toc-label\" aria-hidden=\"true\">{{flavour:flavour-1}}</span><span data-text=\"contents\">{{flavour:contents}}</span></h3>"
    }
  ],
  "flavour": {
    "flavourStrings": [
      {
        "id": "policy",
        "neutral": "Policy ",
        "localised": []
      },
      {
        "id": "draft",
        "neutral": "Draft",
        "localised": []
      },
      {
        "id": "what-this-covers",
        "neutral": "What this covers",
        "localised": []
      },
      {
        "id": "policy-details",
        "neutral": "Policy details",
        "localised": []
      },
      {
        "id": "flavour-1",
        "neutral": "Policy",
        "localised": []
      },
      {
        "id": "contents",
        "neutral": "Contents",
        "localised": []
      }
    ],
    "packVersion": 1
  },
  "note": {
    "themeId": "insurance",
    "noteVersion": 1,
    "supportedFeatures": [
      {
        "feature": "hooks-contract",
        "basis": "measured",
        "by": "build.mjs --verify-pack",
        "at": "2026-09-05"
      }
    ],
    "accessibility": {
      "contrast": "AA",
      "motion": "reduced-motion-aware",
      "keyboard": "reviewed",
      "screenReader": "reviewed",
      "basis": "reviewed"
    },
    "limitations": [],
    "languageCoverage": [
      "en"
    ],
    "contentVersion": "v0.1",
    "lastCheck": {
      "at": "2025-09-05",
      "linter": "build.mjs",
      "result": "passed",
      "failedRules": []
    }
  }
});
})(window.PlusAISpecThemes);
