/*! Generated by build.mjs from packs/ibm-manual/manifest.json — do not edit. */
(function (registry) {
  registry.register("ibm-manual", {
  "packId": "ibm-manual",
  "version": 1,
  "hash": "",
  "languages": [
    "*"
  ],
  "accessibility": {
    "contrast": "AA",
    "reducedMotion": true,
    "notes": "Migrated from the legacy ibm-manual.html page; parity verified by build.mjs --verify-pack."
  },
  "conformanceChecked": "2026-09-05",
  "assets": [
    "theme.css",
    "flavour.json",
    "note.json"
  ],
  "name": {
    "en": "Ibm Manual"
  },
  "maintainer": "JAPER Technology",
  "license": "Project contribution terms (docs/development/0007-licensing-and-mark-policy)",
  "tokens": {
    "accent": "#0057B8",
    "font": "IBM Plex Sans",
    "fontStack": "\"IBM Plex Sans\", ui-sans-serif, -apple-system, BlinkMacSystemFont, \"Segoe UI\", Helvetica, Arial, \"Noto Sans\", \"Noto Sans Arabic\", \"Noto Sans Hebrew\", \"Noto Sans Bengali\", \"Noto Sans Gujarati\", \"Noto Sans Gurmukhi\", \"Noto Sans Tamil\", \"Noto Sans Telugu\", \"Noto Sans Kannada\", \"Noto Sans Malayalam\", \"Noto Sans Thai\", \"Noto Sans Ethiopic\", \"Noto Sans SC\", \"Noto Sans JP\", \"Noto Sans KR\", sans-serif",
    "fontOptions": [],
    "defaultMode": "light",
    "onAccentDark": "#111013",
    "onAccentLight": "#FFFFFF",
    "onAccentThreshold": 0.179,
    "themeColor": "#0057B8"
  },
  "decorations": [
    {
      "op": "wrapInner",
      "anchor": ".site-header",
      "before": "<div class=\"header-top\">",
      "after": "</div>"
    },
    {
      "op": "insertAfter",
      "anchor": ".wordmark",
      "html": "<div class=\"pub-block\"><span class=\"pub-number\">{{flavour:plus-artificial-intelligence}}</span><span class=\"pub-edition\"><span data-text=\"statusLabel\">{{flavour:status}}</span>: <span data-text=\"statusValue\">{{flavour:draft}}</span>&nbsp;·&nbsp;<span data-text=\"versionLabel\">{{flavour:version}}</span>: 0.1</span></div>"
    }
  ],
  "flavour": {
    "flavourStrings": [
      {
        "id": "plus-artificial-intelligence",
        "neutral": "plus-artificial-intelligence.org",
        "localised": []
      },
      {
        "id": "status",
        "neutral": "Status",
        "localised": []
      },
      {
        "id": "draft",
        "neutral": "Draft",
        "localised": []
      },
      {
        "id": "version",
        "neutral": "Version",
        "localised": []
      }
    ],
    "packVersion": 1
  },
  "note": {
    "themeId": "ibm-manual",
    "noteVersion": 1,
    "supportedFeatures": [
      {
        "feature": "hooks-contract",
        "basis": "measured",
        "by": "build.mjs --verify-pack",
        "at": "2026-09-05"
      }
    ],
    "accessibility": {
      "contrast": "AA",
      "motion": "reduced-motion-aware",
      "keyboard": "reviewed",
      "screenReader": "reviewed",
      "basis": "reviewed"
    },
    "limitations": [],
    "languageCoverage": [
      "en"
    ],
    "contentVersion": "v0.1",
    "lastCheck": {
      "at": "2025-09-05",
      "linter": "build.mjs",
      "result": "passed",
      "failedRules": []
    }
  }
});
})(window.PlusAISpecThemes);
