/*! Generated by build.mjs from packs/manufacturing/manifest.json — do not edit. */
(function (registry) {
  registry.register("manufacturing", {
  "packId": "manufacturing",
  "version": 1,
  "hash": "",
  "languages": [
    "*"
  ],
  "accessibility": {
    "contrast": "AA",
    "reducedMotion": true,
    "notes": "Migrated from the legacy manufacturing.html page; parity verified by build.mjs --verify-pack."
  },
  "conformanceChecked": "2026-09-05",
  "assets": [
    "theme.css",
    "flavour.json",
    "note.json"
  ],
  "name": {
    "en": "Manufacturing"
  },
  "maintainer": "JAPER Technology",
  "license": "Project contribution terms (docs/development/0007-licensing-and-mark-policy)",
  "tokens": {
    "accent": "#00A6C0",
    "font": "Roboto Condensed",
    "fontStack": "\"Roboto Condensed\", ui-sans-serif, -apple-system, BlinkMacSystemFont, \"Segoe UI\", Helvetica, Arial, \"Noto Sans\", \"Noto Sans Arabic\", \"Noto Sans Hebrew\", \"Noto Sans Bengali\", \"Noto Sans Gujarati\", \"Noto Sans Gurmukhi\", \"Noto Sans Tamil\", \"Noto Sans Telugu\", \"Noto Sans Kannada\", \"Noto Sans Malayalam\", \"Noto Sans Thai\", \"Noto Sans Ethiopic\", \"Noto Sans SC\", \"Noto Sans JP\", \"Noto Sans KR\", sans-serif",
    "fontOptions": [],
    "defaultMode": "light",
    "onAccentDark": "#111013",
    "onAccentLight": "#FFFFFF",
    "onAccentThreshold": 0.179,
    "themeColor": "#00A6C0"
  },
  "decorations": [
    {
      "op": "wrapInner",
      "anchor": ".site-header",
      "before": "<div class=\"header-row\">",
      "after": "</div>"
    },
    {
      "op": "insertAfter",
      "anchor": ".wordmark",
      "html": "<span class=\"status-lamps\" aria-hidden=\"true\"><i></i><i></i><i></i></span><span class=\"station-tag\"><span class=\"station-id\">{{flavour:station}}+AI-0.1</span><span class=\"station-status\"><span data-text=\"statusLabel\">{{flavour:status}}</span>:<span class=\"station-value\" data-text=\"statusValue\">{{flavour:draft}}</span></span></span>"
    }
  ],
  "flavour": {
    "flavourStrings": [
      {
        "id": "station",
        "neutral": "STATION ",
        "localised": []
      },
      {
        "id": "status",
        "neutral": "STATUS",
        "localised": []
      },
      {
        "id": "draft",
        "neutral": "DRAFT",
        "localised": []
      }
    ],
    "packVersion": 1
  },
  "note": {
    "themeId": "manufacturing",
    "noteVersion": 1,
    "supportedFeatures": [
      {
        "feature": "hooks-contract",
        "basis": "measured",
        "by": "build.mjs --verify-pack",
        "at": "2026-09-05"
      }
    ],
    "accessibility": {
      "contrast": "AA",
      "motion": "reduced-motion-aware",
      "keyboard": "reviewed",
      "screenReader": "reviewed",
      "basis": "reviewed"
    },
    "limitations": [],
    "languageCoverage": [
      "en"
    ],
    "contentVersion": "v0.1",
    "lastCheck": {
      "at": "2025-09-05",
      "linter": "build.mjs",
      "result": "passed",
      "failedRules": []
    }
  }
});
})(window.PlusAISpecThemes);
