/*! Generated by build.mjs — the pack directory. */
window.PlusAISpecThemeIndex = [
  {
    "code": "accounting",
    "name": "Accounting",
    "url": "index.html?theme=accounting"
  },
  {
    "code": "advertising",
    "name": "Advertising",
    "url": "index.html?theme=advertising"
  },
  {
    "code": "aerospace",
    "name": "Aerospace",
    "url": "index.html?theme=aerospace"
  },
  {
    "code": "architecture",
    "name": "Architecture",
    "url": "index.html?theme=architecture"
  },
  {
    "code": "art-cubism",
    "name": "Cubism",
    "url": "index.html?theme=art-cubism"
  },
  {
    "code": "art-impressionist",
    "name": "Impressionist",
    "url": "index.html?theme=art-impressionist"
  },
  {
    "code": "banking",
    "name": "Banking",
    "url": "index.html?theme=banking"
  },
  {
    "code": "biotech",
    "name": "Biotech",
    "url": "index.html?theme=biotech"
  },
  {
    "code": "bladerunner2049",
    "name": "Bladerunner2049",
    "url": "index.html?theme=bladerunner2049"
  },
  {
    "code": "blueprint",
    "name": "Blueprint",
    "url": "index.html?theme=blueprint"
  },
  {
    "code": "chemicals",
    "name": "Chemicals",
    "url": "index.html?theme=chemicals"
  },
  {
    "code": "construction",
    "name": "Construction",
    "url": "index.html?theme=construction"
  },
  {
    "code": "consulting",
    "name": "Consulting",
    "url": "index.html?theme=consulting"
  },
  {
    "code": "country-ja",
    "name": "Ja",
    "url": "index.html?theme=country-ja"
  },
  {
    "code": "cyberpunk",
    "name": "Cyberpunk",
    "url": "index.html?theme=cyberpunk"
  },
  {
    "code": "dec-manual",
    "name": "Dec Manual",
    "url": "index.html?theme=dec-manual"
  },
  {
    "code": "default",
    "name": "Default",
    "url": "index.html"
  },
  {
    "code": "dental",
    "name": "Dental",
    "url": "index.html?theme=dental"
  },
  {
    "code": "energy",
    "name": "Energy",
    "url": "index.html?theme=energy"
  },
  {
    "code": "finance",
    "name": "Finance",
    "url": "index.html?theme=finance"
  },
  {
    "code": "fintech",
    "name": "Fintech",
    "url": "index.html?theme=fintech"
  },
  {
    "code": "fitness",
    "name": "Fitness",
    "url": "index.html?theme=fitness"
  },
  {
    "code": "games",
    "name": "Games",
    "url": "index.html?theme=games"
  },
  {
    "code": "hal9000",
    "name": "Hal9000",
    "url": "index.html?theme=hal9000"
  },
  {
    "code": "hr",
    "name": "Hr",
    "url": "index.html?theme=hr"
  },
  {
    "code": "ibm-manual",
    "name": "Ibm Manual",
    "url": "index.html?theme=ibm-manual"
  },
  {
    "code": "insurance",
    "name": "Insurance",
    "url": "index.html?theme=insurance"
  },
  {
    "code": "lcars-mono",
    "name": "Lcars Mono",
    "url": "index.html?theme=lcars-mono"
  },
  {
    "code": "legal",
    "name": "Legal",
    "url": "index.html?theme=legal"
  },
  {
    "code": "luxury",
    "name": "Luxury",
    "url": "index.html?theme=luxury"
  },
  {
    "code": "manpage",
    "name": "Manpage",
    "url": "index.html?theme=manpage"
  },
  {
    "code": "manufacturing",
    "name": "Manufacturing",
    "url": "index.html?theme=manufacturing"
  },
  {
    "code": "maritime",
    "name": "Maritime",
    "url": "index.html?theme=maritime"
  },
  {
    "code": "medical",
    "name": "Medical",
    "url": "index.html?theme=medical"
  },
  {
    "code": "mentalhealth",
    "name": "Mentalhealth",
    "url": "index.html?theme=mentalhealth"
  },
  {
    "code": "military-spec",
    "name": "Military Spec",
    "url": "index.html?theme=military-spec"
  },
  {
    "code": "mining",
    "name": "Mining",
    "url": "index.html?theme=mining"
  },
  {
    "code": "museum",
    "name": "Museum",
    "url": "index.html?theme=museum"
  },
  {
    "code": "music",
    "name": "Music",
    "url": "index.html?theme=music"
  },
  {
    "code": "neogenesis",
    "name": "Neogenesis",
    "url": "index.html?theme=neogenesis"
  },
  {
    "code": "neutral",
    "name": "Plain view",
    "url": "index.html?theme=neutral"
  },
  {
    "code": "newsroom",
    "name": "Newsroom",
    "url": "index.html?theme=newsroom"
  },
  {
    "code": "notary",
    "name": "Notary",
    "url": "index.html?theme=notary"
  },
  {
    "code": "occupation-ceo",
    "name": "Ceo",
    "url": "index.html?theme=occupation-ceo"
  },
  {
    "code": "occupation-cfo",
    "name": "Cfo",
    "url": "index.html?theme=occupation-cfo"
  },
  {
    "code": "occupation-cio",
    "name": "Cio",
    "url": "index.html?theme=occupation-cio"
  },
  {
    "code": "occupation-coo",
    "name": "Coo",
    "url": "index.html?theme=occupation-coo"
  },
  {
    "code": "occupation-cto",
    "name": "Cto",
    "url": "index.html?theme=occupation-cto"
  },
  {
    "code": "pharma",
    "name": "Pharma",
    "url": "index.html?theme=pharma"
  },
  {
    "code": "quantumlab",
    "name": "Quantumlab",
    "url": "index.html?theme=quantumlab"
  },
  {
    "code": "realestate",
    "name": "Realestate",
    "url": "index.html?theme=realestate"
  },
  {
    "code": "retro",
    "name": "Retro",
    "url": "index.html?theme=retro"
  },
  {
    "code": "sci-fi-1",
    "name": "Sci Fi 1",
    "url": "index.html?theme=sci-fi-1"
  },
  {
    "code": "sci-fi-2",
    "name": "Sci Fi 2",
    "url": "index.html?theme=sci-fi-2"
  },
  {
    "code": "spaceinvaders",
    "name": "Spaceinvaders",
    "url": "index.html?theme=spaceinvaders"
  },
  {
    "code": "spaceodyssey",
    "name": "Spaceodyssey",
    "url": "index.html?theme=spaceodyssey"
  },
  {
    "code": "startrek",
    "name": "Startrek",
    "url": "index.html?theme=startrek"
  },
  {
    "code": "starwars",
    "name": "Starwars",
    "url": "index.html?theme=starwars"
  },
  {
    "code": "swiss",
    "name": "Swiss",
    "url": "index.html?theme=swiss"
  },
  {
    "code": "the-borg",
    "name": "The Borg",
    "url": "index.html?theme=the-borg"
  },
  {
    "code": "theme-adobe",
    "name": "Adobe",
    "url": "index.html?theme=theme-adobe"
  },
  {
    "code": "theme-anthropic",
    "name": "Anthropic",
    "url": "index.html?theme=theme-anthropic"
  },
  {
    "code": "theme-github",
    "name": "Github",
    "url": "index.html?theme=theme-github"
  },
  {
    "code": "theme-google",
    "name": "Google",
    "url": "index.html?theme=theme-google"
  },
  {
    "code": "theme-microsoft",
    "name": "Microsoft",
    "url": "index.html?theme=theme-microsoft"
  },
  {
    "code": "theme-openai",
    "name": "Openai",
    "url": "index.html?theme=theme-openai"
  },
  {
    "code": "theme-youtube",
    "name": "Youtube",
    "url": "index.html?theme=theme-youtube"
  },
  {
    "code": "toolkit",
    "name": "Developer toolkit",
    "url": "index.html?theme=toolkit"
  },
  {
    "code": "university",
    "name": "University",
    "url": "index.html?theme=university"
  },
  {
    "code": "utilities",
    "name": "Utilities",
    "url": "index.html?theme=utilities"
  },
  {
    "code": "veterinary",
    "name": "Veterinary",
    "url": "index.html?theme=veterinary"
  }
];
