/*! Generated by build.mjs from packs/neutral/manifest.json — do not edit. */
(function (registry) {
  registry.register("neutral", {
  "packId": "neutral",
  "version": 1,
  "hash": "",
  "languages": [
    "*"
  ],
  "accessibility": {
    "contrast": "AA",
    "reducedMotion": true,
    "notes": "The accessibility-floor plain view: high contrast, no decoration, no motion. Budget: this pack's own CSS stays far below the 100 KB neutral-route budget (docs/development/0001 D1); the shared engine remains the single-file baseline."
  },
  "conformanceChecked": "2025-09-05",
  "assets": [
    "theme.css",
    "flavour.json",
    "note.json"
  ],
  "name": {
    "en": "Plain view"
  },
  "maintainer": "JAPER Technology",
  "license": "Project contribution terms (docs/development/0007-licensing-and-mark-policy)",
  "tokens": {
    "accent": "#0052CC",
    "font": "Inter",
    "fontStack": "Inter, ui-sans-serif, -apple-system, BlinkMacSystemFont, \"Segoe UI\", Helvetica, Arial, \"Noto Sans\", \"Noto Sans Arabic\", \"Noto Sans Hebrew\", \"Noto Sans Bengali\", \"Noto Sans Gujarati\", \"Noto Sans Gurmukhi\", \"Noto Sans Tamil\", \"Noto Sans Telugu\", \"Noto Sans Kannada\", \"Noto Sans Malayalam\", \"Noto Sans Thai\", \"Noto Sans Ethiopic\", \"Noto Sans SC\", \"Noto Sans JP\", \"Noto Sans KR\", sans-serif",
    "fontOptions": [],
    "defaultMode": "light",
    "onAccentDark": "#111111",
    "onAccentLight": "#FFFFFF",
    "onAccentThreshold": 0.179,
    "themeColor": "#0052CC"
  },
  "decorations": [],
  "script": "",
  "flavour": {
    "flavourStrings": [],
    "packVersion": 1
  },
  "note": {
    "themeId": "neutral",
    "noteVersion": 1,
    "supportedFeatures": [
      {
        "feature": "hooks-contract",
        "basis": "measured",
        "by": "build.mjs --verify-pack",
        "at": "2025-09-05"
      },
      {
        "feature": "accessibility-floor",
        "basis": "reviewed",
        "by": "maintainer",
        "at": "2025-09-05"
      }
    ],
    "accessibility": {
      "contrast": "AA",
      "motion": "no-motion",
      "keyboard": "complete",
      "screenReader": "complete",
      "basis": "reviewed"
    },
    "limitations": [
      {
        "limitation": "No theme-specific decoration by design.",
        "fallback": "itself — the neutral route",
        "blocker": false
      }
    ],
    "languageCoverage": [
      "en"
    ],
    "contentVersion": "v0.1",
    "lastCheck": {
      "at": "2025-09-05",
      "linter": "build.mjs",
      "result": "passed",
      "failedRules": []
    }
  }
});
})(window.PlusAISpecThemes);
