/*! Generated by build.mjs from packs/theme-youtube/manifest.json — do not edit. */
(function (registry) {
  registry.register("theme-youtube", {
  "packId": "theme-youtube",
  "version": 1,
  "hash": "",
  "languages": [
    "*"
  ],
  "accessibility": {
    "contrast": "AA",
    "reducedMotion": true,
    "notes": "Migrated from the legacy theme-youtube.html page; parity verified by build.mjs --verify-pack."
  },
  "conformanceChecked": "2026-09-05",
  "assets": [
    "theme.css",
    "flavour.json",
    "note.json"
  ],
  "name": {
    "en": "Youtube"
  },
  "maintainer": "JAPER Technology",
  "license": "Project contribution terms (docs/development/0007-licensing-and-mark-policy)",
  "tokens": {
    "accent": "#FF0000",
    "font": "Roboto",
    "fontStack": "Roboto, ui-sans-serif, -apple-system, BlinkMacSystemFont, \"Segoe UI\", Helvetica, Arial, \"Noto Sans\", \"Noto Sans Arabic\", \"Noto Sans Hebrew\", \"Noto Sans Bengali\", \"Noto Sans Gujarati\", \"Noto Sans Gurmukhi\", \"Noto Sans Tamil\", \"Noto Sans Telugu\", \"Noto Sans Kannada\", \"Noto Sans Malayalam\", \"Noto Sans Thai\", \"Noto Sans Ethiopic\", \"Noto Sans SC\", \"Noto Sans JP\", \"Noto Sans KR\", sans-serif",
    "fontOptions": [],
    "defaultMode": "dark",
    "onAccentDark": "#111013",
    "onAccentLight": "#FFFFFF",
    "onAccentThreshold": 0.179,
    "themeColor": "#FF0000"
  },
  "decorations": [
    {
      "op": "insertAfter",
      "anchor": ".wordmark",
      "html": "<div class=\"search-pill\" aria-hidden=\"true\"><svg class=\"search-glyph\" viewBox=\"0 0 24 24\" width=\"15\" height=\"15\" aria-hidden=\"true\"><circle cx=\"11\" cy=\"11\" r=\"7\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\"></circle><line x1=\"16.5\" y1=\"16.5\" x2=\"21\" y2=\"21\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\"></line></svg><span class=\"search-placeholder\">{{flavour:search}}</span><span class=\"search-key\">/</span></div>"
    },
    {
      "op": "remove",
      "anchor": "#heroTitle"
    },
    {
      "op": "prependTo",
      "anchor": "#meaning",
      "html": "<div class=\"player\"><div class=\"player-stage\"><span class=\"glyph glyph-tl\" aria-hidden=\"true\">◀◀</span><span class=\"glyph glyph-tr\" aria-hidden=\"true\">▶▶</span><h1 id=\"heroTitle\" class=\"player-mark\"><span class=\"mark\">+AI</span></h1><span class=\"glyph glyph-bl\" aria-hidden=\"true\">{{flavour:vol}}</span><span class=\"glyph glyph-br\" aria-hidden=\"true\">{{flavour:hd}}</span></div><div class=\"player-bar\" aria-hidden=\"true\"><span class=\"player-bar-buffered\"></span><span class=\"player-bar-progress\"></span><span class=\"player-bar-knob\"></span></div></div>"
    },
    {
      "op": "insertAfter",
      "anchor": ".player",
      "html": "<div class=\"hero-meta\"></div>"
    },
    {
      "op": "move",
      "anchor": ".hero-meta",
      "target": ".hero-copy"
    },
    {
      "op": "move",
      "anchor": ".hero-meta",
      "target": ".meaning-card"
    },
    {
      "op": "appendTo",
      "anchor": ".meaning-card",
      "html": "<div class=\"meaning-more\" aria-hidden=\"true\"></div>"
    }
  ],
  "flavour": {
    "flavourStrings": [
      {
        "id": "search",
        "neutral": "Search",
        "localised": []
      },
      {
        "id": "vol",
        "neutral": "VOL",
        "localised": []
      },
      {
        "id": "hd",
        "neutral": "HD",
        "localised": []
      }
    ],
    "packVersion": 1
  },
  "note": {
    "themeId": "theme-youtube",
    "noteVersion": 1,
    "supportedFeatures": [
      {
        "feature": "hooks-contract",
        "basis": "measured",
        "by": "build.mjs --verify-pack",
        "at": "2026-09-05"
      }
    ],
    "accessibility": {
      "contrast": "AA",
      "motion": "reduced-motion-aware",
      "keyboard": "reviewed",
      "screenReader": "reviewed",
      "basis": "reviewed"
    },
    "limitations": [
      {
        "limitation": "Flavour copy is English-only at migration; other languages fall back to English via the flavour mechanism.",
        "fallback": "neutral pack",
        "blocker": false
      }
    ],
    "languageCoverage": [
      "en"
    ],
    "contentVersion": "v0.1",
    "lastCheck": {
      "at": "2025-09-05",
      "linter": "build.mjs",
      "result": "passed",
      "failedRules": []
    }
  }
});
})(window.PlusAISpecThemes);
