/*! Generated by build.mjs from packs/architecture/manifest.json — do not edit. */
(function (registry) {
  registry.register("architecture", {
  "packId": "architecture",
  "version": 1,
  "hash": "",
  "languages": [
    "*"
  ],
  "accessibility": {
    "contrast": "AA",
    "reducedMotion": true,
    "notes": "Migrated from the legacy architecture.html page; parity verified by build.mjs --verify-pack."
  },
  "conformanceChecked": "2026-09-05",
  "assets": [
    "theme.css",
    "flavour.json",
    "note.json"
  ],
  "name": {
    "en": "Architecture"
  },
  "maintainer": "JAPER Technology",
  "license": "Project contribution terms (docs/development/0007-licensing-and-mark-policy)",
  "tokens": {
    "accent": "#35618E",
    "font": "Jost",
    "fontStack": "Jost, ui-sans-serif, -apple-system, BlinkMacSystemFont, \"Segoe UI\", Helvetica, Arial, \"Noto Sans\", \"Noto Sans Arabic\", \"Noto Sans Hebrew\", \"Noto Sans Bengali\", \"Noto Sans Gujarati\", \"Noto Sans Gurmukhi\", \"Noto Sans Tamil\", \"Noto Sans Telugu\", \"Noto Sans Kannada\", \"Noto Sans Malayalam\", \"Noto Sans Thai\", \"Noto Sans Ethiopic\", \"Noto Sans SC\", \"Noto Sans JP\", \"Noto Sans KR\", sans-serif",
    "fontOptions": [],
    "defaultMode": "light",
    "onAccentDark": "#17181A",
    "onAccentLight": "#FFFFFF",
    "onAccentThreshold": 0.179,
    "themeColor": "#35618E"
  },
  "decorations": [
    {
      "op": "insertAfter",
      "anchor": ".reading-progress",
      "html": "<div class=\"sheet\" aria-hidden=\"true\"><i class=\"corner corner-1\"></i><i class=\"corner corner-2\"></i><i class=\"corner corner-3\"></i><i class=\"corner corner-4\"></i></div>"
    },
    {
      "op": "prependTo",
      "anchor": "#meaning",
      "html": "<div class=\"title-block\" aria-hidden=\"true\"><div class=\"tb-brand\">+AI</div><div class=\"tb-rows\"><span><span data-text=\"specification\">{{flavour:specification}}</span></span><span><span data-text=\"statusLabel\">{{flavour:status}}</span><b data-text=\"statusValue\">{{flavour:draft}}</b></span><span><span data-text=\"versionLabel\">{{flavour:version}}</span><b>0.1</b></span><span>{{flavour:scale}}<b>1:1</b></span><span>{{flavour:sheet}}<b>01/01</b></span></div></div>"
    },
    {
      "op": "insertAfter",
      "anchor": "#heroTitle",
      "html": "<div class=\"hero-rule\" aria-hidden=\"true\"></div>"
    },
    {
      "op": "wrap",
      "anchor": ".meaning-card",
      "before": "<div class=\"hero-aside\"><div class=\"figure-frame\" aria-hidden=\"true\"><span class=\"figure-caption\">{{flavour:fig-01}}</span></div>",
      "after": "</div>"
    },
    {
      "op": "insertAfter",
      "anchor": ".title-block",
      "html": "<div class=\"hero-grid\"></div>"
    },
    {
      "op": "move",
      "anchor": ".hero-grid",
      "target": ".hero-copy"
    },
    {
      "op": "move",
      "anchor": ".hero-grid",
      "target": ".hero-aside"
    }
  ],
  "flavour": {
    "flavourStrings": [
      {
        "id": "specification",
        "neutral": "Specification",
        "localised": []
      },
      {
        "id": "status",
        "neutral": "Status",
        "localised": []
      },
      {
        "id": "draft",
        "neutral": "Draft",
        "localised": []
      },
      {
        "id": "version",
        "neutral": "Version",
        "localised": []
      },
      {
        "id": "scale",
        "neutral": "Scale",
        "localised": []
      },
      {
        "id": "sheet",
        "neutral": "Sheet",
        "localised": []
      },
      {
        "id": "fig-01",
        "neutral": "FIG. 01",
        "localised": []
      }
    ],
    "packVersion": 1
  },
  "note": {
    "themeId": "architecture",
    "noteVersion": 1,
    "supportedFeatures": [
      {
        "feature": "hooks-contract",
        "basis": "measured",
        "by": "build.mjs --verify-pack",
        "at": "2026-09-05"
      }
    ],
    "accessibility": {
      "contrast": "AA",
      "motion": "reduced-motion-aware",
      "keyboard": "reviewed",
      "screenReader": "reviewed",
      "basis": "reviewed"
    },
    "limitations": [],
    "languageCoverage": [
      "en"
    ],
    "contentVersion": "v0.1",
    "lastCheck": {
      "at": "2025-09-05",
      "linter": "build.mjs",
      "result": "passed",
      "failedRules": []
    }
  }
});
})(window.PlusAISpecThemes);
