/*! Generated by build.mjs from packs/the-borg/manifest.json — do not edit. */
(function (registry) {
  registry.register("the-borg", {
  "packId": "the-borg",
  "version": 1,
  "hash": "",
  "languages": [
    "*"
  ],
  "accessibility": {
    "contrast": "AA",
    "reducedMotion": true,
    "notes": "Migrated from the legacy the-borg.html page; parity verified by build.mjs --verify-pack."
  },
  "conformanceChecked": "2026-09-05",
  "assets": [
    "theme.css",
    "flavour.json",
    "note.json"
  ],
  "name": {
    "en": "The Borg"
  },
  "maintainer": "JAPER Technology",
  "license": "Project contribution terms (docs/development/0007-licensing-and-mark-policy)",
  "tokens": {
    "accent": "#2EFF5B",
    "font": "Rajdhani",
    "fontStack": "Rajdhani, \"IBM Plex Mono\", ui-sans-serif, -apple-system, BlinkMacSystemFont, \"Segoe UI\", Helvetica, Arial, \"Noto Sans\", \"Noto Sans Arabic\", \"Noto Sans Hebrew\", \"Noto Sans Bengali\", \"Noto Sans Gujarati\", \"Noto Sans Gurmukhi\", \"Noto Sans Tamil\", \"Noto Sans Telugu\", \"Noto Sans Kannada\", \"Noto Sans Malayalam\", \"Noto Sans Thai\", \"Noto Sans Ethiopic\", \"Noto Sans SC\", \"Noto Sans JP\", \"Noto Sans KR\", sans-serif",
    "fontOptions": [
      "Alegreya",
      "Arimo",
      "Assistant",
      "Cairo",
      "Catamaran",
      "Cormorant Garamond",
      "EB Garamond",
      "Exo 2",
      "Frank Ruhl Libre",
      "Heebo",
      "IBM Plex Mono",
      "IBM Plex Sans",
      "Inter",
      "Jost",
      "Jura",
      "Lato",
      "Libre Baskerville",
      "Lora",
      "Manrope",
      "Merriweather",
      "Montserrat",
      "Mukta",
      "Noto Sans",
      "Noto Serif",
      "Nunito Sans",
      "Open Sans",
      "Oswald",
      "Playfair Display",
      "Poppins",
      "PT Sans",
      "Rajdhani",
      "Raleway",
      "Roboto",
      "Roboto Condensed",
      "Roboto Slab",
      "Rubik",
      "Source Sans 3",
      "Spectral",
      "Tinos",
      "Ubuntu",
      "Work Sans"
    ],
    "defaultMode": "dark",
    "onAccentDark": "#111013",
    "onAccentLight": "#FFFFFF",
    "onAccentThreshold": 0.179,
    "themeColor": "#2EFF5B"
  },
  "decorations": [
    {
      "op": "text",
      "anchor": ".hero-subtitle",
      "html": "RESISTANCE IS FUTILE — AI HELPED.<br>YOU WILL TAKE RESPONSIBILITY."
    },
    {
      "op": "text",
      "anchor": ".hero-lead",
      "html": "WE ARE THE +AI COLLECTIVE. <strong>YOUR DISTINCTIVENESS — AND YOUR ACCOUNTABILITY — WILL BE ADDED TO OUR OWN.</strong>"
    },
    {
      "op": "text",
      "anchor": ".primary-link",
      "html": "ASSIMILATE THE SPEC"
    },
    {
      "op": "text",
      "anchor": "#meaningTitle",
      "html": "COLLECTIVE DIRECTIVES"
    },
    {
      "op": "text",
      "anchor": "#specTitle",
      "html": "+AI <span data-text=\"specification\">DIRECTIVES</span>"
    },
    {
      "op": "text",
      "anchor": ".spec-meta",
      "html": "<dt data-text=\"statusLabel\">STATUS</dt> <dd data-text=\"statusValue\">ASSIMILATED</dd> <dt data-text=\"versionLabel\">VERSION</dt> <dd>0.1</dd> <dt data-text=\"markLabel\">DESIGNATION</dt> <dd>RESPONSIBLE PARTY</dd>"
    },
    {
      "op": "text",
      "anchor": "#tocTitle",
      "html": "COLLECTIVE INDEX"
    },
    {
      "op": "text",
      "anchor": "#untranslatedBadge",
      "html": "ADAPTATION IN PROGRESS"
    }
  ],
  "interfaceCopyOverrides": {
    "en": {
      "heroTitle": "RESISTANCE IS FUTILE — AI HELPED. YOU WILL TAKE RESPONSIBILITY.",
      "heroLead": "WE ARE THE +AI COLLECTIVE. <strong>YOUR DISTINCTIVENESS — AND YOUR ACCOUNTABILITY — WILL BE ADDED TO OUR OWN.</strong>",
      "readSpec": "ASSIMILATE THE SPEC",
      "meansHeading": "COLLECTIVE DIRECTIVES",
      "contents": "COLLECTIVE INDEX",
      "specification": "DIRECTIVES",
      "statusLabel": "STATUS",
      "statusValue": "ASSIMILATED",
      "versionLabel": "VERSION",
      "markLabel": "DESIGNATION"
    }
  },
  "untranslatedNoticeOverrides": {
    "en": {
      "badge": "ADAPTATION IN PROGRESS",
      "headline": "This language has not been assimilated. The specification below is shown in English.",
      "detail": "The English text is the normative directive in all cases."
    }
  },
  "endOverride": {
    "en": "<p>+AI Specification v0.1</p><p>Human-AI Provenance and Accountability</p><strong>ASSIMILATION COMPLETE — THE RESPONSIBLE PARTY REMAINS DISTINCT.</strong>"
  },
  "script": "",
  "flavour": {
    "flavourStrings": [
      {
        "id": "resistance-is-futile-ai-help",
        "neutral": "RESISTANCE IS FUTILE — AI HELPED.",
        "localised": []
      },
      {
        "id": "you-will-take-responsibility",
        "neutral": "YOU WILL TAKE RESPONSIBILITY.",
        "localised": []
      },
      {
        "id": "collective",
        "neutral": " COLLECTIVE.",
        "localised": []
      },
      {
        "id": "your-distinctiveness-and-you",
        "neutral": "YOUR DISTINCTIVENESS — AND YOUR ACCOUNTABILITY — WILL BE ADDED TO OUR OWN.",
        "localised": []
      },
      {
        "id": "assimilate-the-spec",
        "neutral": "ASSIMILATE THE SPEC",
        "localised": []
      },
      {
        "id": "collective-directives",
        "neutral": "COLLECTIVE DIRECTIVES",
        "localised": []
      },
      {
        "id": "directives",
        "neutral": "DIRECTIVES",
        "localised": []
      },
      {
        "id": "status",
        "neutral": "STATUS",
        "localised": []
      },
      {
        "id": "assimilated",
        "neutral": "ASSIMILATED",
        "localised": []
      },
      {
        "id": "version",
        "neutral": "VERSION",
        "localised": []
      },
      {
        "id": "designation",
        "neutral": "DESIGNATION",
        "localised": []
      },
      {
        "id": "responsible-party",
        "neutral": "RESPONSIBLE PARTY",
        "localised": []
      },
      {
        "id": "adaptation-in-progress",
        "neutral": "ADAPTATION IN PROGRESS",
        "localised": []
      },
      {
        "id": "collective-index",
        "neutral": "COLLECTIVE INDEX",
        "localised": []
      }
    ],
    "packVersion": 1
  },
  "note": {
    "themeId": "the-borg",
    "noteVersion": 1,
    "supportedFeatures": [
      {
        "feature": "hooks-contract",
        "basis": "measured",
        "by": "build.mjs --verify-pack",
        "at": "2026-09-05"
      }
    ],
    "accessibility": {
      "contrast": "AA",
      "motion": "reduced-motion-aware",
      "keyboard": "reviewed",
      "screenReader": "reviewed",
      "basis": "reviewed"
    },
    "limitations": [
      {
        "limitation": "Flavour copy is English-only at migration; other languages fall back to English via the flavour mechanism.",
        "fallback": "neutral pack",
        "blocker": false
      }
    ],
    "languageCoverage": [
      "en"
    ],
    "contentVersion": "v0.1",
    "lastCheck": {
      "at": "2026-09-05",
      "linter": "build.mjs",
      "result": "pending",
      "failedRules": []
    }
  }
});
})(window.PlusAISpecThemes);
