/*! Generated by build.mjs from packs/country-ja/manifest.json — do not edit. */
(function (registry) {
  registry.register("country-ja", {
  "packId": "country-ja",
  "version": 1,
  "hash": "",
  "languages": [
    "*"
  ],
  "accessibility": {
    "contrast": "AA",
    "reducedMotion": true,
    "notes": "Migrated from the legacy country-ja.html page; parity verified by build.mjs --verify-pack."
  },
  "conformanceChecked": "2026-09-05",
  "assets": [
    "theme.css",
    "flavour.json",
    "note.json"
  ],
  "name": {
    "en": "Ja"
  },
  "maintainer": "JAPER Technology",
  "license": "Project contribution terms (docs/development/0007-licensing-and-mark-policy)",
  "tokens": {
    "accent": "#D04A3C",
    "font": "Noto Sans",
    "fontStack": "\"Noto Sans\", ui-sans-serif, -apple-system, BlinkMacSystemFont, \"Segoe UI\", Helvetica, Arial, \"Noto Sans\", \"Noto Sans Arabic\", \"Noto Sans Hebrew\", \"Noto Sans Bengali\", \"Noto Sans Gujarati\", \"Noto Sans Gurmukhi\", \"Noto Sans Tamil\", \"Noto Sans Telugu\", \"Noto Sans Kannada\", \"Noto Sans Malayalam\", \"Noto Sans Thai\", \"Noto Sans Ethiopic\", \"Noto Sans SC\", \"Noto Sans JP\", \"Noto Sans KR\", sans-serif",
    "fontOptions": [],
    "defaultMode": "light",
    "onAccentDark": "#111013",
    "onAccentLight": "#FFFFFF",
    "onAccentThreshold": 0.179,
    "themeColor": "#D04A3C"
  },
  "decorations": [
    {
      "op": "setAttribute",
      "anchor": "#fontSelect",
      "name": "aria-label",
      "value": "Choose a font"
    },
    {
      "op": "prependTo",
      "anchor": "#meaning",
      "html": "<div class=\"enso\" aria-hidden=\"true\"></div>"
    },
    {
      "op": "wrap",
      "anchor": "#heroTitle",
      "before": "<div class=\"hero-head\">",
      "after": "</div>"
    },
    {
      "op": "move",
      "anchor": ".hero-head",
      "target": ".hero-subtitle"
    },
    {
      "op": "insertBefore",
      "anchor": ".plain-meaning",
      "html": "<div class=\"seigaiha\" aria-hidden=\"true\"></div>"
    },
    {
      "op": "text",
      "anchor": "#specTitle",
      "html": "<span class=\"spec-mark\">+AI</span><span data-text=\"specification\">{{flavour:specification}}</span>"
    },
    {
      "op": "insertAfter",
      "anchor": "#top",
      "html": "<div class=\"seigaiha\" aria-hidden=\"true\"></div>"
    }
  ],
  "flavour": {
    "flavourStrings": [
      {
        "id": "specification",
        "neutral": "Specification",
        "localised": []
      }
    ],
    "packVersion": 1
  },
  "note": {
    "themeId": "country-ja",
    "noteVersion": 1,
    "supportedFeatures": [
      {
        "feature": "hooks-contract",
        "basis": "measured",
        "by": "build.mjs --verify-pack",
        "at": "2026-09-05"
      }
    ],
    "accessibility": {
      "contrast": "AA",
      "motion": "reduced-motion-aware",
      "keyboard": "reviewed",
      "screenReader": "reviewed",
      "basis": "reviewed"
    },
    "limitations": [],
    "languageCoverage": [
      "en"
    ],
    "contentVersion": "v0.1",
    "lastCheck": {
      "at": "2025-09-05",
      "linter": "build.mjs",
      "result": "passed",
      "failedRules": []
    }
  }
});
})(window.PlusAISpecThemes);
