/*! Generated by build.mjs from packs/quantumlab/manifest.json — do not edit. */
(function (registry) {
  registry.register("quantumlab", {
  "packId": "quantumlab",
  "version": 1,
  "hash": "",
  "languages": [
    "*"
  ],
  "accessibility": {
    "contrast": "AA",
    "reducedMotion": true,
    "notes": "Migrated from the legacy quantumlab.html page; parity verified by build.mjs --verify-pack."
  },
  "conformanceChecked": "2026-09-05",
  "assets": [
    "theme.css",
    "flavour.json",
    "note.json"
  ],
  "name": {
    "en": "Quantumlab"
  },
  "maintainer": "JAPER Technology",
  "license": "Project contribution terms (docs/development/0007-licensing-and-mark-policy)",
  "tokens": {
    "accent": "#00C853",
    "font": "Inter",
    "fontStack": "Inter, ui-sans-serif, -apple-system, BlinkMacSystemFont, \"Segoe UI\", Helvetica, Arial, \"Noto Sans\", \"Noto Sans Arabic\", \"Noto Sans Hebrew\", \"Noto Sans Bengali\", \"Noto Sans Gujarati\", \"Noto Sans Gurmukhi\", \"Noto Sans Tamil\", \"Noto Sans Telugu\", \"Noto Sans Kannada\", \"Noto Sans Malayalam\", \"Noto Sans Thai\", \"Noto Sans Ethiopic\", \"Noto Sans SC\", \"Noto Sans JP\", \"Noto Sans KR\", sans-serif",
    "fontOptions": [],
    "defaultMode": "light",
    "onAccentDark": "#111013",
    "onAccentLight": "#FFFFFF",
    "onAccentThreshold": 0.179,
    "themeColor": "#00C853"
  },
  "decorations": [
    {
      "op": "prependTo",
      "anchor": "#meaning",
      "html": "<div class=\"particle-traces\" aria-hidden=\"true\"><span class=\"arc arc-a\"></span><span class=\"arc arc-b\"></span><span class=\"arc arc-c\"></span><span class=\"node node-a\"></span><span class=\"node node-b\"></span><span class=\"node node-c\"></span><span class=\"node node-d\"></span></div>"
    },
    {
      "op": "wrap",
      "anchor": "#heroTitle",
      "before": "<div class=\"mark-figure\" dir=\"ltr\">",
      "after": "</div>"
    },
    {
      "op": "insertAfter",
      "anchor": "#heroTitle",
      "html": "<span class=\"ref-num\" aria-hidden=\"true\">1</span><span class=\"anno anno-top\" aria-hidden=\"true\">{{flavour:canonical-mark-anno}}</span><span class=\"anno anno-side\" aria-hidden=\"true\">→ +AI</span>"
    }
  ],
  "flavour": {
    "flavourStrings": [
      {
        "id": "canonical-mark-anno",
        "neutral": "canonical mark",
        "localised": []
      }
    ],
    "packVersion": 1
  },
  "note": {
    "themeId": "quantumlab",
    "noteVersion": 1,
    "supportedFeatures": [
      {
        "feature": "hooks-contract",
        "basis": "measured",
        "by": "build.mjs --verify-pack",
        "at": "2026-09-05"
      }
    ],
    "accessibility": {
      "contrast": "AA",
      "motion": "reduced-motion-aware",
      "keyboard": "reviewed",
      "screenReader": "reviewed",
      "basis": "reviewed"
    },
    "limitations": [
      {
        "limitation": "Flavour copy is English-only at migration; other languages fall back to English via the flavour mechanism.",
        "fallback": "neutral pack",
        "blocker": false
      }
    ],
    "languageCoverage": [
      "en"
    ],
    "contentVersion": "v0.1",
    "lastCheck": {
      "at": "2025-09-05",
      "linter": "build.mjs",
      "result": "passed",
      "failedRules": []
    }
  }
});
})(window.PlusAISpecThemes);
