/*! Generated by build.mjs from packs/military-spec/manifest.json — do not edit. */
(function (registry) {
  registry.register("military-spec", {
  "packId": "military-spec",
  "version": 1,
  "hash": "",
  "languages": [
    "*"
  ],
  "accessibility": {
    "contrast": "AA",
    "reducedMotion": true,
    "notes": "Migrated from the legacy military-spec.html page; parity verified by build.mjs --verify-pack."
  },
  "conformanceChecked": "2026-09-05",
  "assets": [
    "theme.css",
    "flavour.json",
    "note.json"
  ],
  "name": {
    "en": "Military Spec"
  },
  "maintainer": "JAPER Technology",
  "license": "Project contribution terms (docs/development/0007-licensing-and-mark-policy)",
  "tokens": {
    "accent": "#4B5320",
    "font": "IBM Plex Mono",
    "fontStack": "\"Oswald\", \"IBM Plex Mono\", \"Saira Stencil One\", ui-sans-serif, -apple-system, BlinkMacSystemFont, \"Segoe UI\", Helvetica, Arial, \"Noto Sans\", \"Noto Sans Arabic\", \"Noto Sans Hebrew\", \"Noto Sans Bengali\", \"Noto Sans Gujarati\", \"Noto Sans Gurmukhi\", \"Noto Sans Tamil\", \"Noto Sans Telugu\", \"Noto Sans Kannada\", \"Noto Sans Malayalam\", \"Noto Sans Thai\", \"Noto Sans Ethiopic\", \"Noto Sans SC\", \"Noto Sans JP\", \"Noto Sans KR\", sans-serif",
    "fontOptions": [
      "Alegreya",
      "Arimo",
      "Assistant",
      "Cairo",
      "Catamaran",
      "Cormorant Garamond",
      "EB Garamond",
      "Exo 2",
      "Frank Ruhl Libre",
      "Heebo",
      "IBM Plex Mono",
      "IBM Plex Sans",
      "Inter",
      "Jost",
      "Jura",
      "Lato",
      "Libre Baskerville",
      "Lora",
      "Manrope",
      "Merriweather",
      "Montserrat",
      "Mukta",
      "Noto Sans",
      "Noto Serif",
      "Nunito Sans",
      "Open Sans",
      "Oswald",
      "Playfair Display",
      "Poppins",
      "PT Sans",
      "Raleway",
      "Roboto",
      "Roboto Condensed",
      "Roboto Slab",
      "Rubik",
      "Saira Stencil One",
      "Source Sans 3",
      "Spectral",
      "Tinos",
      "Ubuntu",
      "Work Sans"
    ],
    "defaultMode": "light",
    "onAccentDark": "#111013",
    "onAccentLight": "#FFFFFF",
    "onAccentThreshold": 0.179,
    "themeColor": "#4B5320"
  },
  "decorations": [
    {
      "op": "insertBefore",
      "anchor": ".site-header",
      "html": "<div class=\"classification classification-top\" aria-hidden=\"true\">{{flavour:public-document-no-export-co}}</div><div class=\"doc-strip\"><span class=\"doc-number\">MIL-STD-+AI-0.1</span><span class=\"doc-replaces\">{{flavour:replaces-none}}</span><span class=\"doc-date\">{{flavour:doc-date}}</span></div>"
    },
    {
      "op": "setAttribute",
      "anchor": "#fontSelect",
      "name": "aria-label",
      "value": "Choose a font"
    },
    {
      "op": "text",
      "anchor": ".hero-subtitle",
      "html": "AI HELPED.<br>THE RESPONSIBLE PARTY SHALL REMAIN IDENTIFIED."
    },
    {
      "op": "text",
      "anchor": ".hero-lead",
      "html": "This document establishes the <strong>+AI</strong> mark and its meaning for all deliverables."
    },
    {
      "op": "text",
      "anchor": ".primary-link",
      "html": "Open the standard"
    },
    {
      "op": "text",
      "anchor": "#meaningTitle",
      "html": "Requirements"
    },
    {
      "op": "addClass",
      "anchor": ".spec-kicker",
      "className": "stencil"
    },
    {
      "op": "wrap",
      "anchor": ".spec-meta",
      "before": "<div class=\"spec-meta-wrap\">",
      "after": "</div>"
    },
    {
      "op": "insertAfter",
      "anchor": ".spec-meta",
      "html": "<div class=\"doc-control\"><div class=\"doc-control-row\"><span class=\"doc-control-label\">{{flavour:prepared-by}}</span><span class=\"sig-line\"></span><span class=\"sig-date\">{{flavour:sig-date}}</span></div><div class=\"doc-control-row\"><span class=\"doc-control-label\">{{flavour:reviewed-by}}</span><span class=\"sig-line\"></span><span class=\"sig-date\">{{flavour:sig-date}}</span></div><div class=\"doc-control-row\"><span class=\"doc-control-label\">{{flavour:approved-by}}</span><span class=\"sig-line\"></span><span class=\"sig-date\">{{flavour:sig-date}}</span></div></div>"
    },
    {
      "op": "insertAfter",
      "anchor": ".spec-header",
      "html": "<div class=\"distribution\">{{flavour:distribution-statement-a-app}}</div>"
    },
    {
      "op": "text",
      "anchor": "#untranslatedBadge",
      "html": "{{flavour:change-notice}}"
    },
    {
      "op": "addClass",
      "anchor": "#tocTitle",
      "className": "stencil"
    },
    {
      "op": "text",
      "anchor": "#tocTitle",
      "html": "Table of contents"
    },
    {
      "op": "insertAfter",
      "anchor": "#top",
      "html": "<div class=\"classification classification-bottom\" aria-hidden=\"true\">{{flavour:public-document-no-export-co}}</div>"
    }
  ],
  "flavour": {
    "flavourStrings": [
      {
        "id": "public-document-no-export-co",
        "neutral": "Public Document · No Export Control",
        "localised": []
      },
      {
        "id": "replaces-none",
        "neutral": "Replaces None",
        "localised": []
      },
      {
        "id": "doc-date",
        "neutral": "Date: __________",
        "localised": []
      },
      {
        "id": "sig-date",
        "neutral": "Date: ____",
        "localised": []
      },
      {
        "id": "prepared-by",
        "neutral": "Prepared by",
        "localised": []
      },
      {
        "id": "reviewed-by",
        "neutral": "Reviewed by",
        "localised": []
      },
      {
        "id": "approved-by",
        "neutral": "Approved by",
        "localised": []
      },
      {
        "id": "distribution-statement-a-app",
        "neutral": "DISTRIBUTION STATEMENT A: APPROVED FOR PUBLIC RELEASE — UNLIMITED.",
        "localised": []
      },
      {
        "id": "change-notice",
        "neutral": "Change notice",
        "localised": []
      }
    ],
    "packVersion": 1
  },
  "note": {
    "themeId": "military-spec",
    "noteVersion": 1,
    "supportedFeatures": [
      {
        "feature": "hooks-contract",
        "basis": "measured",
        "by": "build.mjs --verify-pack",
        "at": "2026-09-05"
      }
    ],
    "accessibility": {
      "contrast": "AA",
      "motion": "reduced-motion-aware",
      "keyboard": "reviewed",
      "screenReader": "reviewed",
      "basis": "reviewed"
    },
    "limitations": [
      {
        "limitation": "Flavour copy is English-only at migration; other languages fall back to English via the flavour mechanism.",
        "fallback": "neutral pack",
        "blocker": false
      }
    ],
    "languageCoverage": [
      "en"
    ],
    "contentVersion": "v0.1",
    "lastCheck": {
      "at": "2025-09-05",
      "linter": "build.mjs",
      "result": "passed",
      "failedRules": []
    }
  }
});
})(window.PlusAISpecThemes);
