/*! Generated by build.mjs from packs/consulting/manifest.json — do not edit. */
(function (registry) {
  registry.register("consulting", {
  "packId": "consulting",
  "version": 1,
  "hash": "",
  "languages": [
    "*"
  ],
  "accessibility": {
    "contrast": "AA",
    "reducedMotion": true,
    "notes": "Migrated from the legacy consulting.html page; parity verified by build.mjs --verify-pack."
  },
  "conformanceChecked": "2026-09-05",
  "assets": [
    "theme.css",
    "flavour.json",
    "note.json"
  ],
  "name": {
    "en": "Consulting"
  },
  "maintainer": "JAPER Technology",
  "license": "Project contribution terms (docs/development/0007-licensing-and-mark-policy)",
  "tokens": {
    "accent": "#2456A6",
    "font": "IBM Plex Sans",
    "fontStack": "\"IBM Plex Sans\", ui-sans-serif, -apple-system, BlinkMacSystemFont, \"Segoe UI\", Helvetica, Arial, \"Noto Sans\", \"Noto Sans Arabic\", \"Noto Sans Hebrew\", \"Noto Sans Bengali\", \"Noto Sans Gujarati\", \"Noto Sans Gurmukhi\", \"Noto Sans Tamil\", \"Noto Sans Telugu\", \"Noto Sans Kannada\", \"Noto Sans Malayalam\", \"Noto Sans Thai\", \"Noto Sans Ethiopic\", \"Noto Sans SC\", \"Noto Sans JP\", \"Noto Sans KR\", sans-serif",
    "fontOptions": [],
    "defaultMode": "light",
    "onAccentDark": "#111013",
    "onAccentLight": "#FFFFFF",
    "onAccentThreshold": 0.179,
    "themeColor": "#2456A6"
  },
  "decorations": [
    {
      "op": "insertAfter",
      "anchor": ".meaning-card",
      "html": "<div class=\"matrix\" aria-hidden=\"true\"><span class=\"matrix-y\">{{flavour:ai-participation}}</span><div class=\"matrix-grid\"><span class=\"matrix-cell\">—</span><span class=\"matrix-cell matrix-mark\">+AI</span><span class=\"matrix-cell\">—</span><span class=\"matrix-cell\">—</span></div><span class=\"matrix-x\">{{flavour:human-adoption}}</span></div><div class=\"slide-footer\" aria-hidden=\"true\">+AI ·<span data-text=\"specification\">{{flavour:specification}}</span>{{flavour:0-1-page-01}}</div>"
    }
  ],
  "flavour": {
    "flavourStrings": [
      {
        "id": "ai-participation",
        "neutral": "AI PARTICIPATION",
        "localised": []
      },
      {
        "id": "human-adoption",
        "neutral": "HUMAN ADOPTION",
        "localised": []
      },
      {
        "id": "specification",
        "neutral": "Specification",
        "localised": []
      },
      {
        "id": "0-1-page-01",
        "neutral": "0.1 · PAGE 01",
        "localised": []
      }
    ],
    "packVersion": 1
  },
  "note": {
    "themeId": "consulting",
    "noteVersion": 1,
    "supportedFeatures": [
      {
        "feature": "hooks-contract",
        "basis": "measured",
        "by": "build.mjs --verify-pack",
        "at": "2026-09-05"
      }
    ],
    "accessibility": {
      "contrast": "AA",
      "motion": "reduced-motion-aware",
      "keyboard": "reviewed",
      "screenReader": "reviewed",
      "basis": "reviewed"
    },
    "limitations": [],
    "languageCoverage": [
      "en"
    ],
    "contentVersion": "v0.1",
    "lastCheck": {
      "at": "2025-09-05",
      "linter": "build.mjs",
      "result": "passed",
      "failedRules": []
    }
  }
});
})(window.PlusAISpecThemes);
