/*! Generated by build.mjs from packs/startrek/manifest.json — do not edit. */
(function (registry) {
  registry.register("startrek", {
  "packId": "startrek",
  "version": 1,
  "hash": "",
  "languages": [
    "*"
  ],
  "accessibility": {
    "contrast": "AA",
    "reducedMotion": true,
    "notes": "Migrated from the legacy startrek.html page; parity verified by build.mjs --verify-pack."
  },
  "conformanceChecked": "2026-09-05",
  "assets": [
    "theme.css",
    "flavour.json",
    "note.json"
  ],
  "name": {
    "en": "Startrek"
  },
  "maintainer": "JAPER Technology",
  "license": "Project contribution terms (docs/development/0007-licensing-and-mark-policy)",
  "tokens": {
    "accent": "#FF9C00",
    "font": "Oswald",
    "fontStack": "Oswald, \"Antonio\", Inter, ui-sans-serif, -apple-system, BlinkMacSystemFont, \"Segoe UI\", Helvetica, Arial, \"Noto Sans\", \"Noto Sans Arabic\", \"Noto Sans Hebrew\", \"Noto Sans Bengali\", \"Noto Sans Gujarati\", \"Noto Sans Gurmukhi\", \"Noto Sans Tamil\", \"Noto Sans Telugu\", \"Noto Sans Kannada\", \"Noto Sans Malayalam\", \"Noto Sans Thai\", \"Noto Sans Ethiopic\", \"Noto Sans SC\", \"Noto Sans JP\", \"Noto Sans KR\", sans-serif",
    "fontOptions": [
      "Alegreya",
      "Antonio",
      "Arimo",
      "Assistant",
      "Cairo",
      "Catamaran",
      "Cormorant Garamond",
      "EB Garamond",
      "Exo 2",
      "Frank Ruhl Libre",
      "Heebo",
      "IBM Plex Sans",
      "Inter",
      "Jost",
      "Jura",
      "Lato",
      "Libre Baskerville",
      "Lora",
      "Manrope",
      "Merriweather",
      "Montserrat",
      "Mukta",
      "Noto Sans",
      "Noto Serif",
      "Nunito Sans",
      "Open Sans",
      "Oswald",
      "Playfair Display",
      "Poppins",
      "PT Sans",
      "Raleway",
      "Roboto",
      "Roboto Condensed",
      "Roboto Slab",
      "Rubik",
      "Source Sans 3",
      "Spectral",
      "Tinos",
      "Ubuntu",
      "Work Sans"
    ],
    "defaultMode": "dark",
    "onAccentDark": "#17131A",
    "onAccentLight": "#FFFFFF",
    "onAccentThreshold": 0.179,
    "themeColor": "#FF9C00"
  },
  "decorations": [
    {
      "op": "setAttribute",
      "anchor": "#fontSelect",
      "name": "aria-label",
      "value": "Choose a font"
    },
    {
      "op": "insertBefore",
      "anchor": ".skip-link",
      "html": "<div class=\"starfield\" aria-hidden=\"true\"></div><div class=\"scanlines\" aria-hidden=\"true\"></div><div class=\"sweep\" aria-hidden=\"true\"></div>"
    },
    {
      "op": "prependTo",
      "anchor": ".site-header",
      "html": "<div class=\"lcars-strip\" aria-hidden=\"true\"><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i></div>"
    },
    {
      "op": "wrap",
      "anchor": ".wordmark",
      "before": "<div class=\"header-row\">",
      "after": "</div>"
    },
    {
      "op": "insertAfter",
      "anchor": ".wordmark",
      "html": "<span class=\"chip chip-blue\" aria-hidden=\"true\"></span> <span class=\"chip chip-mauve\" aria-hidden=\"true\"></span> <div class=\"clock-block\" aria-hidden=\"true\"><span class=\"stardate\" id=\"lcarsStardate\">{{flavour:stardate}}</span> <span class=\"clock\" id=\"lcarsClock\">--:--:--</span></div>"
    },
    {
      "op": "move",
      "anchor": ".header-row",
      "target": ".header-controls"
    },
    {
      "op": "appendTo",
      "anchor": ".header-controls",
      "html": "<button class=\"control\" id=\"audioToggle\" type=\"button\" aria-label=\"Toggle interface sound\" aria-pressed=\"false\">{{flavour:audio}}</button>"
    },
    {
      "op": "text",
      "anchor": "footer",
      "html": "<span class=\"footer-left\"><span class=\"status-dot\" aria-hidden=\"true\"></span> <span data-text=\"footerLine\">Open notation. Human responsibility.</span></span> <span>+AI · <span data-text=\"versionFooter\">Specification v0.1</span></span>"
    },
    {
      "op": "text",
      "anchor": "#themeToggle",
      "html": "<span>Dark mode</span>"
    }
  ],
  "script": "behaviour.js",
  "flavour": {
    "flavourStrings": [
      {
        "id": "stardate",
        "neutral": "STARDATE —",
        "localised": []
      },
      {
        "id": "language",
        "neutral": "Language",
        "localised": []
      },
      {
        "id": "english",
        "neutral": "English",
        "localised": []
      },
      {
        "id": "arabic",
        "neutral": "Arabic / العربية",
        "localised": []
      },
      {
        "id": "bengali",
        "neutral": "Bengali / বাংলা",
        "localised": []
      },
      {
        "id": "cantonese",
        "neutral": "Cantonese / 粵語",
        "localised": []
      },
      {
        "id": "dutch-nederlands",
        "neutral": "Dutch / Nederlands",
        "localised": []
      },
      {
        "id": "filipino-filipino",
        "neutral": "Filipino / Filipino",
        "localised": []
      },
      {
        "id": "french-fran-ais",
        "neutral": "French / Français",
        "localised": []
      },
      {
        "id": "german-deutsch",
        "neutral": "German / Deutsch",
        "localised": []
      },
      {
        "id": "greek",
        "neutral": "Greek / Ελληνικά",
        "localised": []
      },
      {
        "id": "gujarati",
        "neutral": "Gujarati / ગુજરાતી",
        "localised": []
      },
      {
        "id": "hausa-hausa",
        "neutral": "Hausa / Hausa",
        "localised": []
      },
      {
        "id": "hebrew",
        "neutral": "Hebrew / עברית",
        "localised": []
      },
      {
        "id": "hindi",
        "neutral": "Hindi / हिन्दी",
        "localised": []
      },
      {
        "id": "indonesian-bahasa-indonesia",
        "neutral": "Indonesian / Bahasa Indonesia",
        "localised": []
      },
      {
        "id": "italian-italiano",
        "neutral": "Italian / Italiano",
        "localised": []
      },
      {
        "id": "japanese",
        "neutral": "Japanese / 日本語",
        "localised": []
      },
      {
        "id": "javanese-basa-jawa",
        "neutral": "Javanese / Basa Jawa",
        "localised": []
      },
      {
        "id": "kannada",
        "neutral": "Kannada / ಕನ್ನಡ",
        "localised": []
      },
      {
        "id": "korean",
        "neutral": "Korean / 한국어",
        "localised": []
      },
      {
        "id": "malay-bahasa-melayu",
        "neutral": "Malay / Bahasa Melayu",
        "localised": []
      },
      {
        "id": "malayalam",
        "neutral": "Malayalam / മലയാളം",
        "localised": []
      },
      {
        "id": "mandarin",
        "neutral": "Mandarin / 中文",
        "localised": []
      },
      {
        "id": "marathi",
        "neutral": "Marathi / मराठी",
        "localised": []
      },
      {
        "id": "pashto",
        "neutral": "Pashto / پښتو",
        "localised": []
      },
      {
        "id": "persian",
        "neutral": "Persian / فارسی",
        "localised": []
      },
      {
        "id": "polish-polski",
        "neutral": "Polish / Polski",
        "localised": []
      },
      {
        "id": "portuguese-portugu-s",
        "neutral": "Portuguese / Português",
        "localised": []
      },
      {
        "id": "punjabi",
        "neutral": "Punjabi / ਪੰਜਾਬੀ",
        "localised": []
      },
      {
        "id": "romanian-rom-n",
        "neutral": "Romanian / Română",
        "localised": []
      },
      {
        "id": "russian",
        "neutral": "Russian / Русский",
        "localised": []
      },
      {
        "id": "spanish-espa-ol",
        "neutral": "Spanish / Español",
        "localised": []
      },
      {
        "id": "swahili-kiswahili",
        "neutral": "Swahili / Kiswahili",
        "localised": []
      },
      {
        "id": "tamil",
        "neutral": "Tamil / தமிழ்",
        "localised": []
      },
      {
        "id": "telugu",
        "neutral": "Telugu / తెలుగు",
        "localised": []
      },
      {
        "id": "thai",
        "neutral": "Thai / ไทย",
        "localised": []
      },
      {
        "id": "turkish-t-rk-e",
        "neutral": "Turkish / Türkçe",
        "localised": []
      },
      {
        "id": "ukrainian",
        "neutral": "Ukrainian / Українська",
        "localised": []
      },
      {
        "id": "urdu",
        "neutral": "Urdu / اردو",
        "localised": []
      },
      {
        "id": "vietnamese-ti-ng-vi-t",
        "neutral": "Vietnamese / Tiếng Việt",
        "localised": []
      },
      {
        "id": "amharic",
        "neutral": "Amharic / አማርኛ",
        "localised": []
      },
      {
        "id": "font",
        "neutral": "Font",
        "localised": []
      },
      {
        "id": "current-font",
        "neutral": "Current Font",
        "localised": []
      },
      {
        "id": "dark-mode",
        "neutral": "Dark mode",
        "localised": []
      },
      {
        "id": "highlight",
        "neutral": "Highlight",
        "localised": []
      },
      {
        "id": "audio",
        "neutral": "Audio",
        "localised": []
      },
      {
        "id": "post-nominal-description",
        "neutral": " Post Nominal Description",
        "localised": []
      },
      {
        "id": "ai-helped",
        "neutral": "AI helped.",
        "localised": []
      },
      {
        "id": "i-take-responsibility",
        "neutral": "I take responsibility.",
        "localised": []
      },
      {
        "id": "the-person-or-organisation-w",
        "neutral": "The person or organisation whose name carried this link is making a simple declaration:",
        "localised": []
      },
      {
        "id": "artificial-intelligence-mate",
        "neutral": "artificial intelligence materially assisted the work, and they accept responsibility for releasing it.",
        "localised": []
      },
      {
        "id": "read-the-specification",
        "neutral": "Read the specification",
        "localised": []
      },
      {
        "id": "what-the-mark-says",
        "neutral": "What the mark says",
        "localised": []
      },
      {
        "id": "ai-participated",
        "neutral": "AI participated",
        "localised": []
      },
      {
        "id": "ai-materially-helped-create-",
        "neutral": "AI materially helped create, analyse, transform or present the work.",
        "localised": []
      },
      {
        "id": "a-human-chose",
        "neutral": "A human chose",
        "localised": []
      },
      {
        "id": "a-person-or-organisation-kno",
        "neutral": "A person or organisation knowingly adopted and released the result.",
        "localised": []
      },
      {
        "id": "responsibility-stays-human",
        "neutral": "Responsibility stays human",
        "localised": []
      },
      {
        "id": "the-named-party-does-not-tra",
        "neutral": "The named party does not transfer accountability to an AI system or provider.",
        "localised": []
      },
      {
        "id": "transparent-assistance",
        "neutral": "Transparent assistance.",
        "localised": []
      },
      {
        "id": "visible-accountability",
        "neutral": "Visible accountability.",
        "localised": []
      },
      {
        "id": "the-mark-is-an-accountabilit",
        "neutral": "The mark is an accountability declaration, not a claim that AI is the author and not a guarantee that the work is correct.",
        "localised": []
      },
      {
        "id": "it-does-not-say-how-much-of-",
        "neutral": "It does not say how much of the work came from AI. It says AI materially influenced the result and an identifiable person or organisation stands behind the decision to use it.",
        "localised": []
      },
      {
        "id": "three-characters-make-both-p",
        "neutral": "Three characters make both participation and responsibility visible.",
        "localised": []
      },
      {
        "id": "full-document",
        "neutral": "Full document",
        "localised": []
      },
      {
        "id": "specification",
        "neutral": "Specification",
        "localised": []
      },
      {
        "id": "status",
        "neutral": "Status",
        "localised": []
      },
      {
        "id": "draft",
        "neutral": "Draft",
        "localised": []
      },
      {
        "id": "version",
        "neutral": "Version",
        "localised": []
      },
      {
        "id": "canonical-mark",
        "neutral": "Canonical mark",
        "localised": []
      },
      {
        "id": "not-translated",
        "neutral": "Not translated",
        "localised": []
      },
      {
        "id": "contents",
        "neutral": "Contents",
        "localised": []
      },
      {
        "id": "open-notation-human-responsi",
        "neutral": "Open notation. Human responsibility.",
        "localised": []
      },
      {
        "id": "specification-v0-1",
        "neutral": "Specification v0.1",
        "localised": []
      },
      {
        "id": "javascript-is-required-for-l",
        "neutral": "JavaScript is required for language switching and interactive colour controls. The canonical specification is available in",
        "localised": []
      },
      {
        "id": "specification-md",
        "neutral": "SPECIFICATION.md",
        "localised": []
      }
    ],
    "packVersion": 1
  },
  "note": {
    "themeId": "startrek",
    "noteVersion": 1,
    "supportedFeatures": [
      {
        "feature": "hooks-contract",
        "basis": "measured",
        "by": "build.mjs --verify-pack",
        "at": "2026-09-05"
      }
    ],
    "accessibility": {
      "contrast": "AA",
      "motion": "reduced-motion-aware",
      "keyboard": "reviewed",
      "screenReader": "reviewed",
      "basis": "reviewed"
    },
    "limitations": [
      {
        "limitation": "Flavour copy is English-only at migration; other languages fall back to English via the flavour mechanism.",
        "fallback": "neutral pack",
        "blocker": false
      }
    ],
    "languageCoverage": [
      "en"
    ],
    "contentVersion": "v0.1",
    "lastCheck": {
      "at": "2026-09-05",
      "linter": "build.mjs",
      "result": "pending",
      "failedRules": []
    }
  }
});
})(window.PlusAISpecThemes);
