/*! Generated by build.mjs from packs/blueprint/manifest.json — do not edit. */
(function (registry) {
  registry.register("blueprint", {
  "packId": "blueprint",
  "version": 1,
  "hash": "",
  "languages": [
    "*"
  ],
  "accessibility": {
    "contrast": "AA",
    "reducedMotion": true,
    "notes": "Migrated from the legacy blueprint.html page; parity verified by build.mjs --verify-pack."
  },
  "conformanceChecked": "2026-09-05",
  "assets": [
    "theme.css",
    "flavour.json",
    "note.json"
  ],
  "name": {
    "en": "Blueprint"
  },
  "maintainer": "JAPER Technology",
  "license": "Project contribution terms (docs/development/0007-licensing-and-mark-policy)",
  "tokens": {
    "accent": "#FFC53D",
    "font": "Oswald",
    "fontStack": "Oswald, \"Antonio\", Inter, ui-sans-serif, -apple-system, BlinkMacSystemFont, \"Segoe UI\", Helvetica, Arial, \"Noto Sans\", \"Noto Sans Arabic\", \"Noto Sans Hebrew\", \"Noto Sans Bengali\", \"Noto Sans Gujarati\", \"Noto Sans Gurmukhi\", \"Noto Sans Tamil\", \"Noto Sans Telugu\", \"Noto Sans Kannada\", \"Noto Sans Malayalam\", \"Noto Sans Thai\", \"Noto Sans Ethiopic\", \"Noto Sans SC\", \"Noto Sans JP\", \"Noto Sans KR\", sans-serif",
    "fontOptions": [
      "Alegreya",
      "Antonio",
      "Arimo",
      "Assistant",
      "Cairo",
      "Catamaran",
      "Cormorant Garamond",
      "EB Garamond",
      "Exo 2",
      "Frank Ruhl Libre",
      "Heebo",
      "IBM Plex Sans",
      "Inter",
      "Jost",
      "Jura",
      "Lato",
      "Libre Baskerville",
      "Lora",
      "Manrope",
      "Merriweather",
      "Montserrat",
      "Mukta",
      "Noto Sans",
      "Noto Serif",
      "Nunito Sans",
      "Open Sans",
      "Oswald",
      "Playfair Display",
      "Poppins",
      "PT Sans",
      "Raleway",
      "Roboto",
      "Roboto Condensed",
      "Roboto Slab",
      "Rubik",
      "Source Sans 3",
      "Spectral",
      "Tinos",
      "Ubuntu",
      "Work Sans"
    ],
    "defaultMode": "dark",
    "onAccentDark": "#111013",
    "onAccentLight": "#FFFFFF",
    "onAccentThreshold": 0.179,
    "themeColor": "#FFC53D"
  },
  "decorations": [
    {
      "op": "insertBefore",
      "anchor": ".skip-link",
      "html": "<div class=\"sheet\" aria-hidden=\"true\"><span class=\"sheet-frame\"></span><span class=\"reg-mark reg-tl\"></span><span class=\"reg-mark reg-tr\"></span><span class=\"reg-mark reg-bl\"></span><span class=\"reg-mark reg-br\"></span></div>"
    },
    {
      "op": "wrapInner",
      "anchor": ".site-header",
      "before": "<div class=\"header-row\">",
      "after": "</div>"
    },
    {
      "op": "wrapInner",
      "anchor": "footer",
      "before": "<div class=\"title-block\"><div class=\"tb-head\"><span class=\"tb-title\">+AI<span data-text=\"specification\">{{flavour:specification}}</span></span><span class=\"tb-sub\">Human-AI Provenance &amp; Accountability</span></div><div class=\"tb-cells\"><span class=\"tb-cell\"><b data-text=\"statusLabel\">{{flavour:status}}</b><i data-text=\"statusValue\">{{flavour:draft}}</i></span><span class=\"tb-cell\"><b data-text=\"versionLabel\">{{flavour:version}}</b><i>0.1</i></span><span class=\"tb-cell\"><b>{{flavour:scale}}</b><i>1:1</i></span><span class=\"tb-cell\"><b>{{flavour:sheet}}</b><i>1 / 1</i></span></div><div class=\"tb-foot\">",
      "after": "</div></div>"
    }
  ],
  "flavour": {
    "flavourStrings": [
      {
        "id": "specification",
        "neutral": "Specification",
        "localised": []
      },
      {
        "id": "status",
        "neutral": "Status",
        "localised": []
      },
      {
        "id": "draft",
        "neutral": "Draft",
        "localised": []
      },
      {
        "id": "version",
        "neutral": "Version",
        "localised": []
      },
      {
        "id": "scale",
        "neutral": "Scale",
        "localised": []
      },
      {
        "id": "sheet",
        "neutral": "Sheet",
        "localised": []
      }
    ],
    "packVersion": 1
  },
  "note": {
    "themeId": "blueprint",
    "noteVersion": 1,
    "supportedFeatures": [
      {
        "feature": "hooks-contract",
        "basis": "measured",
        "by": "build.mjs --verify-pack",
        "at": "2026-09-05"
      }
    ],
    "accessibility": {
      "contrast": "AA",
      "motion": "reduced-motion-aware",
      "keyboard": "reviewed",
      "screenReader": "reviewed",
      "basis": "reviewed"
    },
    "limitations": [],
    "languageCoverage": [
      "en"
    ],
    "contentVersion": "v0.1",
    "lastCheck": {
      "at": "2025-09-05",
      "linter": "build.mjs",
      "result": "passed",
      "failedRules": []
    }
  }
});
})(window.PlusAISpecThemes);
