/*! Generated by build.mjs from packs/veterinary/manifest.json — do not edit. */
(function (registry) {
  registry.register("veterinary", {
  "packId": "veterinary",
  "version": 1,
  "hash": "",
  "languages": [
    "*"
  ],
  "accessibility": {
    "contrast": "AA",
    "reducedMotion": true,
    "notes": "Migrated from the legacy veterinary.html page; parity verified by build.mjs --verify-pack."
  },
  "conformanceChecked": "2026-09-05",
  "assets": [
    "theme.css",
    "flavour.json",
    "note.json"
  ],
  "name": {
    "en": "Veterinary"
  },
  "maintainer": "JAPER Technology",
  "license": "Project contribution terms (docs/development/0007-licensing-and-mark-policy)",
  "tokens": {
    "accent": "#2AA198",
    "font": "Catamaran",
    "fontStack": "Catamaran, ui-sans-serif, -apple-system, BlinkMacSystemFont, \"Segoe UI\", Helvetica, Arial, \"Noto Sans\", \"Noto Sans Arabic\", \"Noto Sans Hebrew\", \"Noto Sans Bengali\", \"Noto Sans Gujarati\", \"Noto Sans Gurmukhi\", \"Noto Sans Tamil\", \"Noto Sans Telugu\", \"Noto Sans Kannada\", \"Noto Sans Malayalam\", \"Noto Sans Thai\", \"Noto Sans Ethiopic\", \"Noto Sans SC\", \"Noto Sans JP\", \"Noto Sans KR\", sans-serif",
    "fontOptions": [],
    "defaultMode": "light",
    "onAccentDark": "#111013",
    "onAccentLight": "#FFFFFF",
    "onAccentThreshold": 0.179,
    "themeColor": "#2AA198"
  },
  "decorations": [
    {
      "op": "text",
      "anchor": ".wordmark",
      "html": "+AI<span class=\"paw paw-dot\" aria-hidden=\"true\"></span>"
    },
    {
      "op": "wrap",
      "anchor": ".wordmark",
      "before": "<div class=\"header-brand\">",
      "after": "</div>"
    },
    {
      "op": "insertAfter",
      "anchor": ".wordmark",
      "html": "<p class=\"record-line\"><span class=\"record-prefix\" aria-hidden=\"true\">{{flavour:record}} +AI-0.1 · </span><span data-text=\"statusValue\">Draft</span></p>"
    },
    {
      "op": "insertAfter",
      "anchor": ".primary-link",
      "html": "<span class=\"paw hero-signature\" aria-hidden=\"true\"></span>"
    },
    {
      "op": "text",
      "anchor": "footer",
      "html": "<span class=\"footer-left\"><span class=\"paw footer-paw\" aria-hidden=\"true\"></span> <span data-text=\"footerLine\">Open notation. Human responsibility.</span></span> <span>+AI · <span data-text=\"versionFooter\">Specification v0.1</span></span>"
    }
  ],
  "flavour": {
    "flavourStrings": [
      {
        "id": "draft",
        "neutral": "Draft",
        "localised": []
      },
      {
        "id": "record",
        "neutral": "RECORD",
        "localised": []
      }
    ],
    "packVersion": 1
  },
  "note": {
    "themeId": "veterinary",
    "noteVersion": 1,
    "supportedFeatures": [
      {
        "feature": "hooks-contract",
        "basis": "measured",
        "by": "build.mjs --verify-pack",
        "at": "2026-09-05"
      }
    ],
    "accessibility": {
      "contrast": "AA",
      "motion": "reduced-motion-aware",
      "keyboard": "reviewed",
      "screenReader": "reviewed",
      "basis": "reviewed"
    },
    "limitations": [
      {
        "limitation": "Flavour copy is English-only at migration; other languages fall back to English via the flavour mechanism.",
        "fallback": "neutral pack",
        "blocker": false
      }
    ],
    "languageCoverage": [
      "en"
    ],
    "contentVersion": "v0.1",
    "lastCheck": {
      "at": "2026-09-05",
      "linter": "build.mjs",
      "result": "pending",
      "failedRules": []
    }
  }
});
})(window.PlusAISpecThemes);
